'use strict';
// Production app / synthetic API fixtures. These screenshots do not claim Windows/LCU evidence.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
const baseline=process.argv.includes('--baseline-perf');const root=path.resolve(__dirname,'..'),web=path.join(root,'backend/web'),out=path.join(root,'docs/history/reports/r231');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'r231-chromium-'));let chrome,ws,server,origin;const errors=[],results=[];
const inject=`
 overview.player.serverId='HN1';if(query.has('foreign')){overview.player.region='jp1';overview.player.serverId='';status.clientRegion='jp1';status.clientRegionLabel='日服';status.serverId='';status.serverName='';}overview.player.playerRef='r231-demo-player';overview.seasonChampionStats=overview.championStats;overview.seasonOverall=overview.overall;overview.seasonStatsProgress.tableSupported=true;overview.masteryChampionCount=37;overview.capabilities.push({name:'champion-mastery',state:'available'});
 const r231Original=structuredClone(overview.matches);
 const r231Matches=Array.from({length:200},(_,i)=>{const match=structuredClone(r231Original[i%r231Original.length]);match.gameId=231000+i;const self=match.participants.find(p=>p.participantId===match.subjectParticipantId)||match.participants[0];self.multiKill=2+i%4;match.result='win';return match;});
 window.__r231Matches=r231Matches;
 const r231Row=(id,games=40,opponents=[])=>({championId:id,championName:({1:'安妮',2:'奥拉夫',3:'加里奥',4:'崔斯特',5:'赵信',6:'厄加特',7:'乐芙兰',8:'弗拉基米尔',9:'费德提克',10:'凯尔'})[id]||'英雄'+id,games,wins:Math.round(games*.6),losses:games-Math.round(games*.6),winRate:60,kda:3.5,kills:7,deaths:3,assists:8,score:7.2,rank:2,kp:.6,damagePerMinute:700,damageShare:.28,tankShare:.2,controlWards:2,wardsPlaced:10,wardsKilled:4,cs:180,csPerMinute:7,gold:15000,goldPerMinute:450,doubleKills:8,tripleKills:4,quadraKills:2,pentaKills:1,opponents});
 const r231Table={available:true,queue:'420',season:'S26',rows:[r231Row(1,40,Array.from({length:21},(_,i)=>r231Row(i+2,21-i))),r231Row(2,30,[r231Row(1,5)]),...Array.from({length:5},(_,i)=>r231Row(i+3,25-i))],overall:r231Row(0,200)};
 const r231JSON=value=>Promise.resolve(new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}}));
`;
const intercept=`
 if(pathname==='/api/gameplay/overview'){window.__r231OverviewReads=(window.__r231OverviewReads||0)+1;const start=Number(params.get('begIndex')||0),count=Number(params.get('count')||20);return r231JSON({...overview,matches:r231Matches.slice(start,start+count),pagination:{begIndex:start,count:Math.min(count,200-start),hasMore:start+count<200}});}
 if(pathname==='/api/gameplay/champion-table'){const data=structuredClone(r231Table);data.queue=params.get('queue')||'420';if(window.__r231TableMode==='fail')return r231JSON({available:false,detail:'日服英雄数据读取失败，请稍后重试'});if(window.__r231TableMode==='empty'){data.rows=[];data.overall=r231Row(0,0)};return r231JSON(data);}
 if(pathname==='/api/gameplay/masteries')return r231JSON({available:true,items:overview.masteries,totalChampions:173,totalPoints:900000,totalScore:89});
 if(pathname==='/api/gameplay/mayhem-rating'){window.__r231RatingReads=(window.__r231RatingReads||0)+1;if(query.has("ratingFail"))return Promise.resolve(new Response("fixture failure",{status:503}));return r231JSON({available:true,rating:2350,marginOfError:18});}
 if(pathname==='/api/gameplay/season-summary')return r231JSON({seasonChampionStats:overview.championStats,seasonOverall:overview.overall,seasonStatsProgress:{...overview.seasonStatsProgress,complete:true},rankedQueues:{}});
`;
async function main(){
 fs.mkdirSync(out,{recursive:true});
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-background-networking','--disable-renderer-backgrounding','--disable-background-timer-throttling','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${temp}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
 const endpoint=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Chrome startup timeout')),20000);chrome.once('error',reject);chrome.stderr.on('data',c=>{output+=c;const m=output.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1])}})});
 ws=new WebSocket(endpoint);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});let seq=0;const pending=new Map();
 const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method))},30000);pending.set(id,[v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)}]);ws.send(JSON.stringify({id,method,params,sessionId}))});
 ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const [r,j]=pending.get(m.id);pending.delete(m.id);m.error?j(Error(JSON.stringify(m.error))):r(m.result)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Fetch.requestPaused'){const url=m.params.request.url,ok=url.startsWith(origin+'/')||url.startsWith('data:');void send(ok?'Fetch.continueRequest':'Fetch.failRequest',{requestId:m.params.requestId,...(ok?{}:{errorReason:'BlockedByClient'})},m.sessionId).catch(()=>{})}});
 server=http.createServer((req,res)=>{const url=new URL(req.url,'http://fixture'),name=url.pathname;
  if(name==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('event: heartbeat\ndata: {}\n\n');const timer=setInterval(()=>res.write('event: heartbeat\ndata: {}\n\n'),2000);req.on('close',()=>clearInterval(timer));return}
  if(name.startsWith('/api/')){const asset=name.includes('image')||name.includes('asset');res.writeHead(200,{'Content-Type':asset?'image/svg+xml':'application/json'});res.end(asset?'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><rect width="40" height="40" fill="#587c83"/><path d="M8 32 20 8 32 32Z" fill="#c8af67"/></svg>':'{}');return}
  const relative=name==='/'?'index.html':name.slice(1),file=path.join(web,relative);if(relative.includes('..')||!fs.existsSync(file)){res.writeHead(404);res.end();return}let data=baseline && ['gameplay.js','gameplay.css','app.js'].includes(relative) ? require('node:child_process').execFileSync('git',['show','HEAD:backend/web/'+relative],{cwd:root}) : fs.readFileSync(file);
  if(relative==='demo-data.js')data=Buffer.from(data.toString().replace('  const fixtures = new Map([',inject+'\n  const fixtures = new Map([').replace('    const params = new URLSearchParams(url.split("?")[1] || "");','    const params = new URLSearchParams(url.split("?")[1] || "");'+intercept));
  res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 async function page(theme,ratingFail=false,foreign=false){const {targetId}=await send('Target.createTarget',{url:'about:blank'}),{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true}),call=(m,p)=>send(m,p,sessionId);
  await call('Page.enable');await call('Page.addScriptToEvaluateOnNewDocument',{source:'try { localStorage.clear(); } catch (_) {}'});await call('Runtime.enable');await call('Fetch.enable',{patterns:[{urlPattern:'*'}]});await call('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
  const until=async expression=>{for(let i=0;i<200;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('timeout '+expression)};
  const shot=async name=>{const s=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,theme+'-'+name+'.png'),Buffer.from(s.data,'base64'))};
  await call('Page.navigate',{url:origin+'/?demo&section=overview'+(ratingFail?'&ratingFail=1':'')+(foreign?'&foreign=1':'')});await until(`document.querySelector('[data-overview-subpage="champion-table"]') && !document.querySelector('[data-section-loading]')`);await evaluate(`document.documentElement.dataset.theme='${theme}';window.__r231RootNodes=['.career-column','.match-list','.summoner-strip'].map(s=>document.querySelector(s));window.__r231Reads=window.__r231OverviewReads;`);return{theme,call,evaluate,until,shot};
 }
 const pages=[];
 for(const theme of (baseline?['dark']:['dark','light'])){
  const p=await page(theme);pages.push(p);if(baseline)continue;
  const measurements=[];
  for(const width of [1280,780]){await p.call('Emulation.setDeviceMetricsOverride',{width,height:1100,deviceScaleFactor:1,mobile:false});{await p.evaluate(`document.querySelector('[data-open-career-dialog]').click()`);await p.until(`document.querySelector('#career-dialog')?.open`)}
   measurements.push(...await p.evaluate(`[...document.querySelectorAll('#career-dialog header')].filter(h=>h.querySelector('.overview-detail-arrow') && h.getBoundingClientRect().height>0).map(h=>{const a=h.querySelector('svg').getBoundingClientRect(),t=h.querySelector('h3').getBoundingClientRect();return {width:${width},title:h.querySelector('h3').textContent,delta:Math.abs((a.top+a.bottom-t.top-t.bottom)/2)}})`));await p.shot('headers-'+width);await p.evaluate(`document.querySelector('#career-dialog').close()`)
  }
  await p.call('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});
  for(const kind of ['masteries','champion-table']){await p.evaluate(`document.querySelector('[data-overview-subpage="${kind}"]').click()`);await p.until(`document.querySelector('.${kind==='masteries'?'mastery-details-grid':'champion-data-table'}')`);if(kind==='champion-table'){
    await p.shot('table-expanded');await p.evaluate(`document.querySelector('tbody tr:last-child').scrollIntoView()`);await p.until(`[...document.querySelectorAll('tr[data-table-row^="champion:"] img')].every(img=>img.getAttribute('src') && img.complete)`);await p.evaluate(`document.querySelector('#app-scroll').scrollTop=0`);await p.evaluate(`window.__r231TableImages=[...document.querySelectorAll('tr[data-table-row^="champion:"] img')];window.__r231TableSources=window.__r231TableImages.map(i=>i.src)`);
    for(let i=0;i<6;i++){await p.evaluate(`document.querySelector('[data-table-expand="${i%2?1:2}"]').click()`);await p.shot('table-frame-'+i);assert.equal(await p.evaluate(`window.__r231TableImages.every((img,i)=>img.isConnected && img.src===window.__r231TableSources[i])`),true)}
  }await p.evaluate(`document.querySelector('[data-overview-return]').click()`);assert.equal(await p.evaluate(`window.__r231RootNodes.every(n=>n.isConnected)`),true);assert.equal(await p.evaluate(`window.__r231OverviewReads===window.__r231Reads`),true)}
  const foreignPage=await page(theme,false,true);for(const mode of ['empty','fail']){await foreignPage.evaluate(`window.__r231TableMode='${mode}';document.querySelector('[data-overview-subpage="champion-table"]').click()`);await foreignPage.until(`document.querySelectorAll('[data-table-queue]').length===3 && !document.querySelector('.overview-detail-page .muted')`);await foreignPage.shot('foreign-table-'+mode);await foreignPage.evaluate(`document.querySelector('[data-overview-return]').click()`)}await p.evaluate(`window.__r231TableMode=''`);
  await p.shot('multikills-2-3-4-5');
  await p.evaluate(`document.querySelector('[data-toggle-match]').click()`);await p.until(`document.querySelector('[data-match-detail="build"]')`);await p.evaluate(`document.querySelector('[data-match-detail="build"]').click()`);await p.until(`document.querySelector('.build-player img')`);
  const point=await p.evaluate(`(()=>{const r=document.querySelector('.build-player img').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await p.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await p.until(`document.querySelector('.global-tooltip')?.textContent.includes('演示玩家')`);await p.shot('build-avatar-tooltip');await p.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:0,y:0});
  await p.evaluate(`document.querySelector('[data-toggle-match]').click();document.querySelector('[data-rank-mmr-trigger]').click()`);await p.evaluate(`document.querySelector('[data-open-career-dialog]').click();document.querySelector('#career-dialog [data-rank-mmr-trigger]').focus()`);await p.until(`document.querySelector('#career-dialog')?.open`);await new Promise(r=>setTimeout(r,100));await p.evaluate(`document.querySelector('#career-dialog [data-rank-mmr-trigger]').focus()`);await p.until(`getComputedStyle(document.querySelector('#career-dialog .rank-mmr-popover')).opacity==='1'`);await p.shot('mayhem-rating-ready');await p.evaluate(`document.querySelector('#career-dialog').close()`);await p.evaluate(`document.querySelector('[data-rank-mmr-trigger]').click()`);
  const failurePage=await page(theme,true);await failurePage.until(`document.querySelector('.rank-mmr-popover')?.textContent.includes('暂不可用')`).catch(async e=>{console.log(await failurePage.evaluate(`({text:document.querySelector('.rank-mmr-popover')?.textContent,reads:window.__r231RatingReads,url:location.href})`));throw e});await failurePage.evaluate(`document.querySelector('[data-open-career-dialog]').click();document.querySelector('#career-dialog [data-rank-mmr-trigger]').focus()`);await failurePage.until(`document.querySelector('#career-dialog')?.open`);await new Promise(r=>setTimeout(r,100));await failurePage.evaluate(`document.querySelector('#career-dialog [data-rank-mmr-trigger]').focus()`);await failurePage.until(`getComputedStyle(document.querySelector('#career-dialog .rank-mmr-popover')).opacity==='1'`);await failurePage.shot('mayhem-rating-failed');
  const heights=await p.evaluate(`[...document.querySelectorAll('.match-entry')].filter(e=>e.getBoundingClientRect().height>0).slice(0,4).map(e=>e.getBoundingClientRect().height)`);
  assert(measurements.length===4 && measurements.every(m=>m.delta<=1),JSON.stringify(measurements));results.push({theme,measurements,heights});
 }
 // Sequentially page to 200 through the actual scroll observer / pagination controls.
 const p=pages[0];await p.evaluate(`document.querySelector('#app-scroll').scrollTop=999999`);
 for(let i=0;i<40;i++){const n=await p.evaluate(`document.querySelectorAll('.match-list>.match-entry').length`);if(n>=200)break;await p.evaluate(`document.querySelector('[data-load-more]')?.click();document.querySelector('#app-scroll').scrollTop=999999`);await new Promise(r=>setTimeout(r,500))}
 await p.until(`document.querySelectorAll('.match-list>.match-entry').length===200`);await p.evaluate(`document.querySelector('#app-scroll').scrollTop=0;window.__r231LongTasks=[];window.__r231Observer=new PerformanceObserver(list=>window.__r231LongTasks.push(...list.getEntries().map(e=>e.duration)));window.__r231Observer.observe({type:'longtask'});window.__r231Start=Date.now();`);
 const duration=60000,end=Date.now()+duration;while(Date.now()<end)await new Promise(r=>setTimeout(r,Math.min(10000,end-Date.now())));
 const perf=await p.evaluate(`({elapsedMs:Date.now()-window.__r231Start,domNodes:document.getElementsByTagName('*').length,images:document.images.length,cards:document.querySelectorAll('.match-entry').length,longTasks:window.__r231LongTasks.length,longTaskMS:window.__r231LongTasks.reduce((n,v)=>n+v,0),visibility:getComputedStyle(document.querySelector('.match-entry')).contentVisibility,intrinsicSize:getComputedStyle(document.querySelector('.match-entry')).containIntrinsicSize})`);assert(perf.longTaskMS<=1000,JSON.stringify(perf));if(!baseline)await p.shot('200-matches');
 const summary={scope:'Production Chromium app with synthetic fixtures; no Windows/LCU or real upstream claims',results,perf,errors};fs.writeFileSync(path.join(out,baseline?'chromium-before.json':'chromium.json'),JSON.stringify(summary,null,2));assert.equal(errors.length,0,JSON.stringify(errors));console.log(JSON.stringify(summary));
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{ws?.close();chrome?.kill();server?.closeAllConnections();server?.close();fs.rmSync(temp,{recursive:true,force:true,maxRetries:8,retryDelay:100})});
