'use strict';
// Production app / synthetic API fixtures. These screenshots do not claim Windows/LCU evidence.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
const baseline=process.argv.includes('--baseline-perf');const root=path.resolve(__dirname,'..'),web=path.join(root,'backend/web'),out=process.env.R235_BROWSER_OUT||path.join(root,'docs/history/reports/r235');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'r235-chromium-'));let chrome,ws,server,origin;const errors=[],results=[];
const inject=`
 if(query.has('startup235'))Object.assign(status,{connected:false,identityReady:false,snapshotReady:false,clientDiscovery:'probe-failed',connectionState:'connecting'});
 overview.player.serverId='HN1';if(query.has('foreign')){overview.player.region='jp1';overview.player.serverId='';status.clientRegion='jp1';status.clientRegionLabel='日服';status.serverId='';status.serverName='';}overview.player.playerRef='r231-demo-player';overview.seasonChampionStats=overview.championStats;overview.seasonOverall=overview.overall;overview.seasonStatsProgress.tableSupported=true;overview.masteryChampionCount=37;overview.capabilities.push({name:'champion-mastery',state:'available'});
 const r231Original=structuredClone(overview.matches);
 const r231Matches=Array.from({length:200},(_,i)=>{const match=structuredClone(r231Original[i%r231Original.length]);match.gameId=231000+i;const self=match.participants.find(p=>p.participantId===match.subjectParticipantId)||match.participants[0];self.multiKill=2+i%4;match.result='win';return match;});
 if(query.has('arena235')) {Object.assign(overview.player,{gameName:'甜甜酱QvQ',displayName:'甜甜酱QvQ',tagLine:'34839'});const base=r231Matches[0],placements=[1,2,4,3,4,5];r231Matches.splice(0,r231Matches.length,...placements.map((place,i)=>({...structuredClone(base),gameId:235000+i,queueId:1750,queueLabel:'斗魂竞技场 3x6',modeGroup:'arena',gameMode:'CHERRY',createdAt:Date.now()-i*60000,result:place<=3?'win':'loss',subjectParticipantId:1,participants:Array.from({length:18},(_,j)=>({...structuredClone(base.participants[j%base.participants.length]),participantId:j+1,subteamId:Math.floor(j/3)+1,placement:j<3?place:Math.floor(j/3)+1,win:j<3?place<=3:Math.floor(j/3)<3}))})));}
 window.__r231Matches=r231Matches;
 const r231Row=(id,games=40,opponents=[])=>({championId:id,championName:({1:'安妮',2:'奥拉夫',3:'加里奥',4:'崔斯特',5:'赵信',6:'厄加特',7:'乐芙兰',8:'弗拉基米尔',9:'费德提克',10:'凯尔'})[id]||'英雄'+id,games,wins:Math.round(games*.6),losses:games-Math.round(games*.6),winRate:60,kda:3.5,kills:7,deaths:3,assists:8,score:7.2,rank:2,kp:.6,damagePerMinute:700,damageShare:.28,tankShare:.2,controlWards:2,wardsPlaced:10,wardsKilled:4,cs:180,csPerMinute:7,gold:15000,goldPerMinute:450,doubleKills:8,tripleKills:4,quadraKills:2,pentaKills:1,opponents});
 for(const match of r231Matches) {const self=match.participants.find(p=>p.participantId===match.subjectParticipantId)||match.participants[0];for(const p of match.participants){p.totalHeal=500;p.timeCCingOthers=30;p.totalDamageShieldedOnTeammates=700;p.damageDealtToTurrets=1200;}Object.assign(self,{soloKills:3,damage:150000,gold:16000,totalHeal:4500,timeCCingOthers:80,totalDamageShieldedOnTeammates:4000,damageDealtToTurrets:4000,killsNearEnemyTurret:10,killsUnderOwnTurret:8,maxCsAdvantageOnLaneOpponent:60,knockEnemyIntoTeamAndKill:6});if(match.gameId%2) {const rival=match.participants.find(p=>p.teamId!==self.teamId);if(rival)rival.damage=200000;}match.mapId=11;}
 const r231Table={available:true,queue:'420',season:'S26',rows:[r231Row(1,40,Array.from({length:21},(_,i)=>r231Row(i+2,21-i))),r231Row(2,30,[r231Row(1,5)]),...Array.from({length:16},(_,i)=>r231Row(i+3,25-i,[r231Row(60+i,5)]))],overall:r231Row(0,200)};
 const r231JSON=value=>Promise.resolve(new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}}));
`;
const intercept=`
 if(pathname==='/api/gameplay/overview'){window.__r231OverviewReads=(window.__r231OverviewReads||0)+1;const start=Number(params.get('begIndex')||0),count=Number(params.get('count')||20);return r231JSON({...overview,matches:r231Matches.slice(start,start+count),pagination:{begIndex:start,count:Math.min(count,r231Matches.length-start),hasMore:start+count<r231Matches.length}});}
 if(pathname==='/api/gameplay/champion-table'){const data=structuredClone(r231Table);data.queue=params.get('queue')||'420';if(window.__r231TableMode==='fail')return r231JSON({available:false,detail:'日服英雄数据读取失败，请稍后重试'});if(window.__r231TableMode==='empty'){data.rows=[];data.overall=r231Row(0,0)};return r231JSON(data);}
 if(pathname==='/api/gameplay/masteries')return r231JSON({available:true,items:overview.masteries,totalChampions:173,totalPoints:900000,totalScore:89});
 if(pathname==='/api/gameplay/mayhem-rating'){window.__r231RatingReads=(window.__r231RatingReads||0)+1;if(query.has("ratingFail") && !window.__r235RatingRetry)return Promise.resolve(new Response("fixture failure",{status:503}));return r231JSON({available:true,rating:2350,marginOfError:18});}
 if(pathname==='/api/gameplay/season-summary')return r231JSON({seasonChampionStats:overview.championStats,seasonOverall:overview.overall,seasonStatsProgress:{...overview.seasonStatsProgress,complete:true},rankedQueues:{}});
`;
async function main(){
 fs.mkdirSync(out,{recursive:true});
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-background-networking','--disable-renderer-backgrounding','--disable-background-timer-throttling','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${temp}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
 const endpoint=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Chrome startup timeout')),20000);chrome.once('error',reject);chrome.stderr.on('data',c=>{output+=c;const m=output.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1])}})});
 ws=new WebSocket(endpoint);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});let seq=0;const pending=new Map();
 const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method))},30000);pending.set(id,[v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)}]);ws.send(JSON.stringify({id,method,params,sessionId}))});
 ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const [r,j]=pending.get(m.id);pending.delete(m.id);m.error?j(Error(JSON.stringify(m.error))):r(m.result)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Fetch.requestPaused'){const url=m.params.request.url,ok=url.startsWith(origin+'/')||url.startsWith('data:');void send(ok?'Fetch.continueRequest':'Fetch.failRequest',{requestId:m.params.requestId,...(ok?{}:{errorReason:'BlockedByClient'})},m.sessionId).catch(()=>{})}});
 server=http.createServer((req,res)=>{const url=new URL(req.url,'http://fixture'),name=url.pathname;
  if(name==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('event: heartbeat\ndata: {}\n\n');const timer=setInterval(()=>res.write('event: heartbeat\ndata: {}\n\n'),2000);req.on('close',()=>clearInterval(timer));return}
  if(name==='/api/license/status'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({state:'ACTIVE',generation:1,message:''}));return}
  if(name.startsWith('/api/')){const asset=name.includes('image')||name.includes('asset');res.writeHead(200,{'Content-Type':asset?'image/svg+xml':'application/json'});res.end(asset?'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><rect width="40" height="40" fill="#587c83"/><path d="M8 32 20 8 32 32Z" fill="#c8af67"/></svg>':'{}');return}
  const relative=name==='/'?'index.html':name.slice(1),file=path.join(web,relative);if(relative.includes('..')||!fs.existsSync(file)){res.writeHead(404);res.end();return}let data=baseline && ['gameplay.js','gameplay.css','app.js'].includes(relative) ? require('node:child_process').execFileSync('git',['show','HEAD:backend/web/'+relative],{cwd:root}) : fs.readFileSync(file);
  if(relative==='demo-data.js')data=Buffer.from(data.toString().replace('  const fixtures = new Map([',inject+'\n  const fixtures = new Map([').replace('    const params = new URLSearchParams(url.split("?")[1] || "");','    const params = new URLSearchParams(url.split("?")[1] || "");'+intercept));
  res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 async function page(theme,ratingFail=false,foreign=false,arena=false,startup=false){const {targetId}=await send('Target.createTarget',{url:'about:blank'}),{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true}),call=(m,p)=>send(m,p,sessionId);
  await call('Page.enable');await call('Page.addScriptToEvaluateOnNewDocument',{source:'try { localStorage.clear(); } catch (_) {}'});await call('Runtime.enable');await call('Fetch.enable',{patterns:[{urlPattern:'*'}]});await call('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
  const until=async expression=>{for(let i=0;i<200;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('timeout '+expression)};
  const shot=async name=>{const s=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,theme+'-'+name+'.png'),Buffer.from(s.data,'base64'))};
  await call('Page.navigate',{url:origin+'/?demo&section=overview'+(ratingFail?'&ratingFail=1':'')+(foreign?'&foreign=1':'')+(arena?'&arena235=1':'')+(startup?'&startup235=1':'')});await until(startup ? `!document.querySelector('#startup-loading').hidden` : `document.querySelector('[data-overview-subpage="champion-table"]') && !document.querySelector('[data-section-loading]')`).catch(async error=>{console.log(JSON.stringify({errors,body:await evaluate('document.body.innerText'),scripts:await evaluate('[...document.scripts].map(s=>s.src)')}));await shot('failure');throw error});await evaluate(`document.documentElement.dataset.theme='${theme}';window.__r231RootNodes=['.career-column','.match-list','.summoner-strip'].map(s=>document.querySelector(s));window.__r231Reads=window.__r231OverviewReads;`);return{theme,call,evaluate,until,shot};
 }

 const pages=[];
 async function recordFrames(p,name,frames) {
  const {targetId}=await send('Target.createTarget',{url:'about:blank'}),{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
  const code=`(async()=>{const canvas=document.createElement('canvas');canvas.width=1280;canvas.height=1100;const ctx=canvas.getContext('2d'),stream=canvas.captureStream(10),chunks=[];const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8'});recorder.ondataavailable=e=>chunks.push(e.data);const done=new Promise(r=>recorder.onstop=r);recorder.start();for(const data of ${JSON.stringify(frames)}){const img=new Image();img.src='data:image/png;base64,'+data;await img.decode();ctx.drawImage(img,0,0);await new Promise(r=>setTimeout(r,100))}recorder.stop();await done;return await new Promise(r=>{const reader=new FileReader();reader.onload=()=>r(reader.result.split(',')[1]);reader.readAsDataURL(new Blob(chunks,{type:'video/webm'}))})})()`;
  const result=await send('Runtime.evaluate',{expression:code,awaitPromise:true,returnByValue:true},sessionId);if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));fs.writeFileSync(path.join(out,p.theme+'-'+name+'.webm'),Buffer.from(result.result.value,'base64'));await send('Target.closeTarget',{targetId});
 }
 for(const theme of ['dark','light']) {
  const p=await page(theme);pages.push(p);
  for(const width of [1280,780]) {
   await p.call('Emulation.setDeviceMetricsOverride',{width,height:1100,deviceScaleFactor:1,mobile:false});
   for(const kind of ['masteries','champion-table']) {
    await p.evaluate(`document.querySelector('[data-overview-subpage="${kind}"]').click()`);await p.until(`document.querySelector('[data-overview-return] svg')`);
    const delta=await p.evaluate(`(()=>{const button=document.querySelector('[data-overview-return]'),a=button.querySelector('svg').getBoundingClientRect(),t=button.querySelector('span').getBoundingClientRect();return Math.abs((a.top+a.bottom-t.top-t.bottom)/2)})()`);assert(delta<=.5,'return arrow '+delta);results.push({theme,width,kind,returnCenterDelta:delta});await p.shot('return-'+kind+'-'+width);
    if(width===1280&&kind==='champion-table') {
     await p.evaluate(`document.querySelector('[data-table-expand="2"]').click();document.querySelector('[data-table-expand="15"]').scrollIntoView({block:'center'})`);
     const before=await p.evaluate(`document.querySelector('[data-table-expand="15"]').getBoundingClientRect().top`),frames=[];
     for(let i=0;i<20;i++) {if(i===10)await p.evaluate(`document.querySelector('[data-table-expand="15"]').click()`);frames.push((await p.call('Page.captureScreenshot',{format:'png'})).data);await new Promise(r=>setTimeout(r,80));}
     const after=await p.evaluate(`document.querySelector('[data-table-expand="15"]').getBoundingClientRect().top`);assert(Math.abs(before-after)<=1,'table anchor '+JSON.stringify({before,after}));results.push({theme,anchorBefore:before,anchorAfter:after});await p.shot('table-anchor');await recordFrames(p,'table-anchor',frames);
     await p.evaluate(`document.querySelector('[data-table-expand="1"]').click();document.querySelector('[data-table-more]').scrollIntoView({block:'center'})`);
     const moreBefore=await p.evaluate(`document.querySelector('[data-table-more]').getBoundingClientRect().top`);await p.evaluate(`document.querySelector('[data-table-more]').click()`);const moreAfter=await p.evaluate(`document.querySelector('[data-table-more]').getBoundingClientRect().top`);assert(Math.abs(moreBefore-moreAfter)<=1);results.push({theme,moreBefore,moreAfter});
    }
    await p.evaluate(`document.querySelector('[data-overview-return]').click()`);
   }
  }
  await p.call('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});
  await p.evaluate(`document.querySelector('#app-scroll').scrollTop=0`);await p.until(`document.querySelector('.match-tags-more:not([hidden])')`).catch(async error=>{console.log(JSON.stringify(await p.evaluate(`({badges:[...document.querySelectorAll('.match-badges')].slice(0,2).map(n=>({html:n.innerHTML,width:n.clientWidth,collection:n.firstElementChild?.clientWidth})),filter:document.querySelector('.match-filterbar')?.textContent,errors:[]})`)));await p.shot('tag-failure');throw error});await p.shot('tags-star-team');
  const contrasts=await p.evaluate(`(()=>{const lum=c=>c.match(/[0-9.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);return [...document.querySelectorAll('.match-data-tag')].slice(0,40).map(n=>{const c=getComputedStyle(n),a=lum(c.color),b=lum(c.backgroundColor);return {label:n.textContent,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)}})})()`);assert(contrasts.every(c=>c.ratio>=4.5),JSON.stringify(contrasts));results.push({theme,contrasts});
  const tagPoint=await p.evaluate(`(()=>{const r=document.querySelector('.match-tags-more:not([hidden])').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);await p.call('Input.dispatchMouseEvent',{type:'mouseMoved',...tagPoint});await p.until(`document.querySelector('.global-tooltip')?.textContent.includes('单杀')`);await new Promise(r=>setTimeout(r,220));await p.shot('tags-overflow-tooltip');await p.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:0,y:0});
  await p.evaluate(`window.dispatchEvent(new CustomEvent('deep-legends:overview-matches',{detail:{account:'r231-demo-player',replace:true,matches:window.__r231Matches,pagination:{filter:'all',count:200,hasMore:false}}}))`);await p.until(`document.querySelectorAll('.match-list>.match-entry').length===200`);
  await p.evaluate(`window.__r235LongTasks=[];window.__r235Observer=new PerformanceObserver(list=>window.__r235LongTasks.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration}))));window.__r235Observer.observe({type:'longtask',buffered:false});window.__r235OriginalNodes=[...document.querySelectorAll('.match-list>.match-entry')];document.querySelector('[data-match-filter="flex"]').click()`);await p.until(`document.querySelector('[data-match-filter="flex"]').getAttribute('aria-pressed')==='true' || document.querySelector('[data-match-filter="flex"]').classList.contains('is-active')`);
  const filterPerf=await p.evaluate(`(async()=>{const start=performance.now();document.querySelector('[data-match-filter="all"]').click();await new Promise(requestAnimationFrame);const duration=performance.now()-start;await new Promise(r=>setTimeout(r,80));return {duration,longTasks:window.__r235LongTasks.filter(e=>e.start>=start&&e.start<start+duration),same:window.__r235OriginalNodes.every(n=>n.isConnected),nodes:document.querySelectorAll('.match-list>.match-entry').length}})()`);assert(filterPerf.same,JSON.stringify(filterPerf));assert(filterPerf.duration<=100,JSON.stringify(filterPerf));assert(filterPerf.longTasks.every(t=>t.duration<=50),JSON.stringify(filterPerf));results.push({theme,filterPerf});
  const failure=await page(theme,true);await failure.call('Emulation.setDeviceMetricsOverride',{width:780,height:1100,deviceScaleFactor:1,mobile:false});await failure.until(`document.querySelector('[data-mayhem-rating-retry]')`);await failure.evaluate(`document.querySelector('[data-open-career-dialog]').click();document.querySelector('#career-dialog [data-rank-mmr-trigger]').focus()`);await new Promise(r=>setTimeout(r,150));await failure.evaluate(`document.querySelector('#career-dialog [data-rank-mmr-trigger]').focus()`);await failure.until(`getComputedStyle(document.querySelector('#career-dialog .rank-mmr-popover')).opacity==='1'`);await failure.shot('mayhem-failure-retry');await failure.evaluate(`window.__r235RatingRetry=true;document.querySelector('#career-dialog [data-mayhem-rating-retry]').click()`);await failure.until(`document.querySelector('#career-dialog .rank-mmr-popover')?.textContent.includes('2,350')`);await failure.shot('mayhem-retry-ready');
  const startupPage=await page(theme,false,false,false,true);await startupPage.shot('startup-overlay');

  const arenaPage=await page(theme,false,false,true);await arenaPage.until(`document.querySelector('.match-entry')?.textContent.includes('3x6')`);assert.equal(await arenaPage.evaluate(`document.querySelector('.summoner-streak')?.textContent || null`),null);await arenaPage.shot('arena-3x6-no-false-streak');

 }
 const summary={scope:'Production Chromium with synthetic fixtures. No Windows/LCU or real upstream claims.',results,errors};fs.writeFileSync(path.join(out,'chromium.json'),JSON.stringify(summary,null,2));assert.equal(errors.length,0,JSON.stringify(errors));console.log(JSON.stringify(summary));
}

main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{ws?.close();chrome?.kill();server?.closeAllConnections();server?.close();fs.rmSync(temp,{recursive:true,force:true,maxRetries:8,retryDelay:100})});
