'use strict';
const { evidencePath, requireEvidence } = require('./local-evidence.cjs');
// Production app / synthetic API fixtures. These screenshots do not claim Windows/LCU evidence.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');
const baseline=process.argv.includes('--baseline-perf'),guardOnly=process.argv.includes('--guard-only');const root=path.resolve(__dirname,'..'),web=path.join(root,'backend/web'),out=process.env.R241_BROWSER_OUT||evidencePath('r241');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'r241-chromium-'));let chrome,ws,server,origin;const errors=[],results=[];
const inject=`
 if(query.has('startup235'))Object.assign(status,{connected:false,identityReady:false,snapshotReady:false,clientDiscovery:'probe-failed',connectionState:'connecting'});
 overview.player.serverId='HN1';if(query.has('foreign')){overview.player.region='jp1';overview.player.serverId='';status.clientRegion='jp1';status.clientRegionLabel='日服';status.serverId='';status.serverName='';}overview.player.playerRef='r231-demo-player';overview.seasonChampionStats=overview.championStats;overview.seasonOverall=overview.overall;overview.seasonStatsProgress.tableSupported=true;overview.masteryChampionCount=37;overview.capabilities.push({name:'champion-mastery',state:'available'});
 const r231Original=structuredClone(overview.matches);
 const r231Matches=Array.from({length:200},(_,i)=>{const match=structuredClone(r231Original[i%r231Original.length]);match.gameId=231000+i;const self=match.participants.find(p=>p.participantId===match.subjectParticipantId)||match.participants[0];self.multiKill=2+i%4;match.result='win';return match;});
 if(query.has('arena235')) {Object.assign(overview.player,{gameName:'甜甜酱QvQ',displayName:'甜甜酱QvQ',tagLine:'34839'});const base=r231Matches[0],placements=[1,2,4,3,4,5];r231Matches.splice(0,r231Matches.length,...placements.map((place,i)=>({...structuredClone(base),gameId:235000+i,queueId:1750,queueLabel:'斗魂竞技场 3x6',modeGroup:'arena',gameMode:'CHERRY',createdAt:Date.now()-i*60000,result:place<=3?'win':'loss',subjectParticipantId:1,participants:Array.from({length:18},(_,j)=>({...structuredClone(base.participants[j%base.participants.length]),participantId:j+1,subteamId:Math.floor(j/3)+1,placement:j<3?place:Math.floor(j/3)+1,win:j<3?place<=3:Math.floor(j/3)<3}))})));}
 window.__r231Matches=r231Matches;
 const r231Row=(id,games=40,opponents=[])=>({championId:id,championName:({1:'安妮',2:'奥拉夫',3:'加里奥',4:'崔斯特',5:'赵信',6:'厄加特',7:'乐芙兰',8:'弗拉基米尔',9:'费德提克',10:'凯尔'})[id]||'英雄'+id,games,wins:Math.round(games*.6),losses:games-Math.round(games*.6),winRate:60,kda:3.5,kills:7,deaths:3,assists:8,score:7.2,rank:2,kp:.6,damagePerMinute:700,damageShare:.28,tankShare:.2,controlWards:2,wardsPlaced:10,wardsKilled:4,cs:180,csPerMinute:7,gold:15000,goldPerMinute:450,doubleKills:8,tripleKills:4,quadraKills:2,pentaKills:1,opponents});
 for(const match of r231Matches) {const self=match.participants.find(p=>p.participantId===match.subjectParticipantId)||match.participants[0];for(const p of match.participants){p.totalHeal=500;p.timeCCingOthers=30;p.totalDamageShieldedOnTeammates=700;p.damageDealtToTurrets=1200;}Object.assign(self,{soloKills:3,damage:150000,gold:16000,totalHeal:4500,timeCCingOthers:80,totalDamageShieldedOnTeammates:4000,damageDealtToTurrets:4000,killsNearEnemyTurret:10,killsUnderOwnTurret:8,maxCsAdvantageOnLaneOpponent:60,knockEnemyIntoTeamAndKill:6});if(match.gameId%2) {const rival=match.participants.find(p=>p.teamId!==self.teamId);if(rival)rival.damage=200000;}match.mapId=11;}
 const modes=[[1750,30,'arena','斗魂竞技场'],[2400,12,'hextech-aram','海克斯大乱斗'],[440,11,'ranked','灵活组排']];for(let i=0;i<r231Matches.length;i++){const m=r231Matches[i],mode=modes[i%3];Object.assign(m,{queueId:mode[0],mapId:mode[1],modeGroup:mode[2],queueLabel:mode[3]});if(mode[1]===30)m.participants.forEach((p,j)=>Object.assign(p,{subteamId:Math.floor(j/2)+1,placement:Math.floor(j/2)+1}));else m.participants.forEach(p=>{delete p.subteamId;delete p.placement});}r231Matches[3].participants.forEach(p=>delete p.score);
 const r231Table={available:true,queue:'420',season:'S26',rows:[r231Row(1,40,Array.from({length:21},(_,i)=>r231Row(i+2,21-i))),r231Row(2,30,[r231Row(1,5)]),...Array.from({length:16},(_,i)=>r231Row(i+3,25-i,[r231Row(60+i,5)]))],overall:r231Row(0,200)};
 const r231JSON=value=>Promise.resolve(new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}}));
`;
const intercept=`
 if(pathname==='/api/gameplay/overview'){window.__r231OverviewReads=(window.__r231OverviewReads||0)+1;const start=Number(params.get('begIndex')||0),count=Number(params.get('count')||20);return r231JSON({...overview,matches:r231Matches.slice(start,start+count),pagination:{begIndex:start,count:Math.min(count,r231Matches.length-start),hasMore:start+count<r231Matches.length}});}
 if(pathname==='/api/gameplay/champion-table'){const data=structuredClone(r231Table);data.queue=params.get('queue')||'420';if(window.__r231TableMode==='fail')return r231JSON({available:false,detail:'日服英雄数据读取失败，请稍后重试'});if(window.__r231TableMode==='empty'){data.rows=[];data.overall=r231Row(0,0)};return r231JSON(data);}
 if(pathname==='/api/gameplay/masteries')return r231JSON({available:true,items:overview.masteries,totalChampions:173,totalPoints:900000,totalScore:89});
 if(pathname==='/api/gameplay/mayhem-rating'){window.__r231RatingReads=(window.__r231RatingReads||0)+1;if(query.has("ratingFail") && !window.__r235RatingRetry)return Promise.resolve(new Response("fixture failure",{status:503}));return r231JSON({available:true,rating:2350,marginOfError:18});}
 if(pathname==='/api/gameplay/season-summary')return r231JSON({seasonChampionStats:overview.championStats,seasonOverall:overview.overall,seasonStatsProgress:{...overview.seasonStatsProgress,complete:true},rankedQueues:{}});
`;
async function main(){
 fs.mkdirSync(out,{recursive:true});
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-background-networking','--disable-renderer-backgrounding','--disable-background-timer-throttling','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${temp}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
 const endpoint=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error('Chrome startup timeout')),20000);chrome.once('error',reject);chrome.stderr.on('data',c=>{output+=c;const m=output.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1])}})});
 ws=new WebSocket(endpoint);await new Promise((r,j)=>{ws.addEventListener('open',r,{once:true});ws.addEventListener('error',j,{once:true})});let seq=0;const pending=new Map();
 const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method))},30000);pending.set(id,[v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)}]);ws.send(JSON.stringify({id,method,params,sessionId}))});
 ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const [r,j]=pending.get(m.id);pending.delete(m.id);m.error?j(Error(JSON.stringify(m.error))):r(m.result)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);if(m.method==='Fetch.requestPaused'){const url=m.params.request.url,ok=url.startsWith(origin+'/')||url.startsWith('data:');void send(ok?'Fetch.continueRequest':'Fetch.failRequest',{requestId:m.params.requestId,...(ok?{}:{errorReason:'BlockedByClient'})},m.sessionId).catch(()=>{})}});
 server=http.createServer((req,res)=>{const url=new URL(req.url,'http://fixture'),name=url.pathname;
  if(name==='/api/events'){res.writeHead(200,{'Content-Type':'text/event-stream'});res.write('event: heartbeat\ndata: {}\n\n');const timer=setInterval(()=>res.write('event: heartbeat\ndata: {}\n\n'),2000);req.on('close',()=>clearInterval(timer));return}
  if(name==='/api/license/status'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({state:'ACTIVE',generation:1,message:''}));return}
  if(name.startsWith('/api/')){const asset=name.includes('image')||name.includes('asset');res.writeHead(200,{'Content-Type':asset?'image/svg+xml':'application/json'});res.end(asset?'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="40"><rect width="40" height="40" fill="#587c83"/><path d="M8 32 20 8 32 32Z" fill="#c8af67"/></svg>':'{}');return}
  const relative=name==='/'?'index.html':name.slice(1),file=path.join(web,relative);if(relative.includes('..')||!fs.existsSync(file)){res.writeHead(404);res.end();return}let data=baseline && ['gameplay.js','gameplay.css'].includes(relative) ? fs.readFileSync(path.join(out,'baseline/backend/web',relative)) : fs.readFileSync(file);
  if(relative==='demo-data.js')data=Buffer.from(data.toString().replace('  const fixtures = new Map([',inject+'\n  const fixtures = new Map([').replace('    const params = new URLSearchParams(url.split("?")[1] || "");','    const params = new URLSearchParams(url.split("?")[1] || "");'+intercept));
  res.writeHead(200,{'Content-Type':({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png'})[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;
 async function page(theme,ratingFail=false,foreign=false,arena=false,startup=false){const {targetId}=await send('Target.createTarget',{url:'about:blank'}),{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true}),call=(m,p)=>send(m,p,sessionId);
  await call('Page.enable');await call('Page.addScriptToEvaluateOnNewDocument',{source:'try { localStorage.clear(); } catch (_) {} window.__r241LongTasks=[];new PerformanceObserver(list=>window.__r241LongTasks.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:"longtask",buffered:true});'});await call('Runtime.enable');await call('Fetch.enable',{patterns:[{urlPattern:'*'}]});await call('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
  const until=async expression=>{for(let i=0;i<200;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,100))}throw Error('timeout '+expression)};
  const shot=async name=>{if(guardOnly)return;const s=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,theme+'-'+name+'.png'),Buffer.from(s.data,'base64'))};
  await call('Page.navigate',{url:origin+'/?demo&section=overview'+(ratingFail?'&ratingFail=1':'')+(foreign?'&foreign=1':'')+(arena?'&arena235=1':'')+(startup?'&startup235=1':'')});await until(startup ? `!document.querySelector('#startup-loading').hidden` : `document.querySelector('[data-overview-subpage="champion-table"]') && !document.querySelector('[data-section-loading]')`).catch(async error=>{console.log(JSON.stringify({errors,body:await evaluate('document.body.innerText'),scripts:await evaluate('[...document.scripts].map(s=>s.src)')}));await shot('failure');throw error});await evaluate(`document.documentElement.dataset.theme='${theme}';window.__r231RootNodes=['.career-column','.match-list','.summoner-strip'].map(s=>document.querySelector(s));window.__r231Reads=window.__r231OverviewReads;`);return{theme,call,evaluate,until,shot};
 }

 for(const theme of guardOnly?['dark']:['dark','light']) {
  const p=await page(theme);
  const contrast=await p.evaluate(`(()=>{const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');function rgb(color){ctx.fillStyle=color;ctx.fillRect(0,0,1,1);return [...ctx.getImageData(0,0,1,1).data].slice(0,3)}function lum(color){return rgb(color).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0)}return [...document.querySelectorAll('.match-data-tag')].map(n=>{const c=getComputedStyle(n),a=lum(c.color),b=lum(c.backgroundColor);return {label:n.textContent,kind:n.className,ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05)}})})()`);
  if(!baseline)assert(contrast.every(c=>c.ratio>=4.5),JSON.stringify(contrast));results.push({theme,contrastMinimum:Math.min(...contrast.map(c=>c.ratio)),contrasts:contrast});
  for(const zoom of guardOnly?[1]:[1,1.5])for(const width of guardOnly?[1280,1920]:[1280,1600,1920,900,780]) {
   if(zoom===1.5&&width<1280)continue;
   await p.call('Emulation.setDeviceMetricsOverride',{width,height:1100,deviceScaleFactor:1,mobile:false});
   await p.evaluate(`document.documentElement.style.setProperty('--ui-zoom','${zoom}');document.querySelector('#app-scroll').scrollTop=0`);
   await new Promise(r=>setTimeout(r,180));
   const layouts=await p.evaluate(`(()=>{return [...document.querySelectorAll('.match-entry')].slice(0,4).map(n=>{const rect=x=>{const r=x.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height}};const items=rect(n.querySelector('.match-items')),tags=n.querySelector('.match-tags-collection'),roster=n.querySelector('.match-players'),stats=rect(n.querySelector('.match-stats'));return {mode:n.querySelector('.match-result-meta strong').textContent,card:rect(n),items,tags:tags?rect(tags):null,gap:roster&&getComputedStyle(roster).display!=='none'?roster.getBoundingClientRect().left-stats.right:null,rosterWidth:roster?.getBoundingClientRect().width,wrap:getComputedStyle(n.querySelector('.match-build')).flexWrap,visible:tags?[...tags.querySelectorAll('[data-match-tag]')].filter(t=>!t.hidden).map(t=>t.textContent):[],hidden:tags?[...tags.querySelectorAll('[data-match-tag]')].filter(t=>t.hidden).map(t=>t.textContent):[]}})})()`);
   if(!baseline)for(const layout of layouts){assert.equal(layout.wrap,'nowrap');if(layout.tags){assert(Math.abs(layout.tags.top-layout.items.top)<=2,JSON.stringify(layout));assert(layout.tags.height<=layout.items.height+.5,JSON.stringify(layout));assert(layout.tags.left>=layout.items.right-1,JSON.stringify(layout));}if(width>=1280&&zoom===1){assert(layout.gap>=60&&layout.gap<=100,JSON.stringify(layout));}}
   results.push({theme,width,zoom,layouts});await p.shot(`${baseline?'before':'after'}-cards-${width}-zoom-${zoom}`);
   if(zoom===1&&!guardOnly)for(let i=0;i<3;i++){const s=await p.call('Page.captureScreenshot',{format:'png',clip:{x:Math.max(0,layouts[i].card.left),y:Math.max(0,layouts[i].card.top),width:Math.max(1,layouts[i].card.width),height:layouts[i].card.height,scale:1}});fs.writeFileSync(path.join(out,`${theme}-${baseline?'before':'after'}-${['arena','aram','rift'][i]}-${width}.png`),Buffer.from(s.data,'base64'));}
  }
  if(baseline||guardOnly)continue;
  await p.call('Emulation.setDeviceMetricsOverride',{width:780,height:1100,deviceScaleFactor:1,mobile:false});
  await p.evaluate(`const card=document.querySelectorAll('.match-entry')[3],main=card.querySelector('.match-main');main.style.width=(card.querySelector('.match-items').getBoundingClientRect().width+36)+'px';card.scrollIntoView({block:'center'});`);await new Promise(r=>setTimeout(r,180));
  const narrow=await p.evaluate(`(()=>{const card=document.querySelectorAll('.match-entry')[3],tags=card.querySelector('.match-tags-collection'),items=card.querySelector('.match-items').getBoundingClientRect(),r=tags.getBoundingClientRect();return {shown:[...tags.querySelectorAll('[data-match-tag]')].filter(n=>!n.hidden).length,more:tags.querySelector('button').textContent,topDelta:r.top-items.top,height:r.height,itemsHeight:items.height}})()`);assert.equal(narrow.shown,0,JSON.stringify(narrow));assert.match(narrow.more,/^\+\d+$/);assert(Math.abs(narrow.topDelta)<=2&&narrow.height<=narrow.itemsHeight);results.push({theme,narrow});await p.shot('only-more-780');await p.evaluate(`document.querySelectorAll('.match-entry')[3].querySelector('.match-main').style.width=''`);

  await p.call('Emulation.setDeviceMetricsOverride',{width:1280,height:1100,deviceScaleFactor:1,mobile:false});await p.evaluate(`document.documentElement.style.setProperty('--ui-zoom','1');document.querySelector('#app-scroll').scrollTop=300`);await new Promise(r=>setTimeout(r,180));
  let point=await p.evaluate(`(()=>{const b=[...document.querySelectorAll('.match-tags-more:not([hidden])')].find(n=>n.getBoundingClientRect().top>150 && n.parentElement.querySelectorAll('[data-match-tag][hidden]').length>5),r=b.getBoundingClientRect();window.__r241More=b;return {x:r.left+r.width/2,y:r.top+r.height/2}})()`);
  await p.call('Input.dispatchMouseEvent',{type:'mouseMoved',...point});await p.until(`!document.querySelector('.match-tags-popover').hidden`);
  const popup=await p.evaluate(`(()=>{const p=document.querySelector('.match-tags-popover'),b=window.__r241More,r=p.getBoundingClientRect(),br=b.getBoundingClientRect();return {placement:p.dataset.placement,body:p.parentElement===document.body,top:r.top,bottom:r.bottom,anchorTop:br.top,left:r.left,right:r.right,triangle:getComputedStyle(p,'::after').content,hidden:[...b.parentElement.querySelectorAll('[data-match-tag]')].filter(n=>n.hidden).map(n=>n.textContent),shown:[...b.parentElement.querySelectorAll('[data-match-tag]')].filter(n=>!n.hidden).map(n=>n.textContent),popup:[...p.children].map(n=>n.textContent),z:+getComputedStyle(p).zIndex,tooltipZ:+getComputedStyle(document.querySelector('.global-tooltip')).zIndex}})()`);assert.equal(popup.placement,'top');assert(popup.bottom<=popup.anchorTop);assert(popup.body);assert.deepEqual(popup.hidden,popup.popup);assert(popup.left>=0&&popup.right<=1280);assert(popup.tooltipZ>popup.z);results.push({theme,popup});await p.shot('popover-top');
  const explanation=await p.evaluate(`(()=>{const n=document.querySelector('.match-tags-popover [data-tooltip]'),r=n.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()`);await p.call('Input.dispatchMouseEvent',{type:'mouseMoved',...explanation});await p.until(`document.querySelector('.global-tooltip').dataset.shown==='true'`);await p.shot('popover-tag-tooltip');
  await p.call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape'});await p.call('Input.dispatchMouseEvent',{type:'mouseMoved',x:0,y:0});
  await p.evaluate(`const row=window.__r241More.parentElement.cloneNode(true);row.id='edge-case-tags';Object.assign(row.style,{position:'fixed',top:'12px',left:'600px',width:'300px',zIndex:'40'});document.body.append(row);window.__r241Edge=row.querySelector('button');window.__r241Edge.focus()`);await p.until(`!document.querySelector('.match-tags-popover').hidden`);assert.equal(await p.evaluate(`document.querySelector('.match-tags-popover').dataset.placement`),'bottom');await p.shot('popover-bottom');await p.evaluate(`document.querySelector('#edge-case-tags').remove()`);

  await p.evaluate(`document.querySelector('#app-scroll').scrollTop=0`);await p.until(`document.querySelector('.match-tags-popover').hidden`);
  await p.evaluate(`window.dispatchEvent(new CustomEvent('deep-legends:overview-matches',{detail:{account:'r231-demo-player',replace:true,matches:window.__r231Matches,pagination:{filter:'all',count:200,hasMore:false}}}))`);await p.until(`document.querySelectorAll('.match-list>.match-entry').length===200`);
  await p.evaluate(`window.__r241OriginalNodes=[...document.querySelectorAll('.match-list>.match-entry')];document.querySelector('[data-match-filter="flex"]').click()`);await p.until(`document.querySelector('[data-match-filter="flex"]').getAttribute('aria-pressed')==='true' || document.querySelector('[data-match-filter="flex"]').classList.contains('is-active')`);
  const perf=await p.evaluate(`(async()=>{const start=performance.now();document.querySelector('[data-match-filter="all"]').click();await new Promise(requestAnimationFrame);return {duration:performance.now()-start,same:window.__r241OriginalNodes.every(n=>n.isConnected),nodes:document.querySelectorAll('.match-list>.match-entry').length,longTasks:window.__r241LongTasks.filter(e=>e.start>=start)}})()`);assert(perf.same&&perf.nodes===200,JSON.stringify(perf));assert(perf.duration<=35.4,JSON.stringify(perf));results.push({theme,filterPerf:perf,initialPeakLongTask:await p.evaluate('Math.max(0,...window.__r241LongTasks.filter(e=>e.start<3000).map(e=>e.duration))')});
 }

 const summary={scope:'Production Chromium with synthetic fixtures. No Windows/LCU or real upstream claims.',results,errors};fs.writeFileSync(path.join(out,baseline?'chromium-before.json':guardOnly?'chromium-guard.json':'chromium.json'),JSON.stringify(summary,null,2));assert.equal(errors.length,0,JSON.stringify(errors));console.log(JSON.stringify({results:results.length,errors:errors.length}));
}

main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{ws?.close();chrome?.kill();server?.closeAllConnections();server?.close();fs.rmSync(temp,{recursive:true,force:true,maxRetries:8,retryDelay:100})});
