'use strict';
// Real public backend and its CSP/assets, with explicit synthetic API fixtures.
const {spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.R266_BROWSER_OUT||path.join(os.tmpdir(),'deep-legends-r266-browser');
const closedSessions=new Set(), canceledRequests=new Set();let canceledInterceptions=0;
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'r266-browser-')),errors=[],violations=[],results=[];let backend,chrome,ws;
const saved={
 'lol-loot-default-match-filter':'solo','lol-loot-mask-names':'true',
 'lol-loot-player-tab-order':'["cn:HN1:riot:搜索测试#","kr:riot:fixture#kr1"]',
 'deep-legends-history-presets-v1':JSON.stringify([{name:'上次常用',conditions:{result:{values:['win'],not:false}}}]),
};
const inject=`window.__r266Base=structuredClone(overview);const source=overview.matches;overview.matches=Array.from({length:1000},(_,i)=>{const m=structuredClone(source[i%source.length]);m.gameId=900000+i;const p=m.participants.find(p=>p.participantId===m.subjectParticipantId);if(p){p.championId=[103,238,157,875,145,92,64,81,254,555,25,69,28,111,61,268,518,245,113,53,27,17,516,3][i%24];p.championName=['阿狸','劫','亚索','瑟提','卡莎','锐雯','李青','伊泽瑞尔','蔚','派克','莫甘娜','卡西奥佩娅','伊芙琳','深海泰坦','发条魔灵','沙皇','妮蔻','艾克','瑟庄妮','布里茨','辛吉德','提莫','奥恩','加里奥'][i%24];}return m;});if(new URLSearchParams(location.search).has('matrix'))overview.matches=['solo','hextech-aram','arena'].map(mode=>{const m=structuredClone(source.find(row=>row.modeGroup===mode)),p=m.participants.find(p=>p.participantId===m.subjectParticipantId);Object.assign(p,{kills:99,deaths:99,assists:99,kda:2});return m;});overview.pagination={begIndex:0,count:1000,hasMore:false};`;
const intercept=`
 if(pathname==='/api/gameplay/overview' && new URLSearchParams(location.search).has('loading') && !window.__r266Delayed) {
  window.__r266Delayed=true;window.__r266HeaderAt=performance.now();const data=structuredClone(overview);data.matches=data.matches.slice(0,20);data.pagination={count:20,hasMore:false};
  data.seasonChampionStats=structuredClone(data.championStats || []);data.seasonOverall=structuredClone(data.overall || {});
  if(new URLSearchParams(location.search).get('loading')==='zero'){data.matches=[];data.seasonChampionStats=[];data.seasonOverall={games:0};}
  data.seasonStatsProgress={season:'2026',complete:true,collecting:false,scanned:Number(data.seasonOverall.games)||0};
  const header={player:data.player,ranks:data.ranks,masteries:data.masteries,matches:[],historyRequested:0,pagination:{count:20,partial:true},capabilities:[],seasonChampionStats:[],seasonOverall:{},seasonStatsProgress:{season:'2026',complete:false,collecting:true,scanned:0}},encoder=new TextEncoder();
  return Promise.resolve(new Response(new ReadableStream({start(c){c.enqueue(encoder.encode(JSON.stringify({type:'cards',overview:header})+'\\n'));setTimeout(()=>{c.enqueue(encoder.encode(JSON.stringify({type:'complete',overview:data})+'\\n'));c.close();},1500)}}),{headers:{'Content-Type':'application/x-ndjson'}}));
 }
`;
async function start(){
 fs.mkdirSync(out,{recursive:true});
 if(!process.env.R266_CARD_SERVER)backend=spawn(process.env.R266_BACKEND||'/tmp/r266-public',['--desktop'],{cwd:root,env:{...process.env,LOL_LOOT_DATA_DIR:path.join(temp,'data')},stdio:['ignore','pipe','pipe']});
 const ready=process.env.R266_CARD_SERVER?JSON.parse(fs.readFileSync(process.env.R266_CARD_SERVER,'utf8')):await new Promise((resolve,reject)=>{let data='';const timer=setTimeout(()=>reject(Error('Backend startup timeout')),20000);backend.once('error',reject);backend.stdout.on('data',c=>{data+=c;for(const line of data.split('\n')){try{const value=JSON.parse(line.replace(/^LOOT_READY /,''));if(value.baseUrl){clearTimeout(timer);resolve(value);return}}catch{}}});backend.once('exit',code=>reject(Error('Backend exited '+code)));});
 const csp=(await fetch(ready.bootstrapUrl)).headers.get('content-security-policy');assert(csp?.includes("script-src 'self'") && !csp.includes('unsafe-inline'));
 chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-sandbox','--disable-background-networking','--disable-renderer-backgrounding','--disable-background-timer-throttling','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${path.join(temp,'chrome')}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
 const endpoint=await new Promise((resolve,reject)=>{let data='';const timer=setTimeout(()=>reject(Error('Chrome startup timeout')),20000);chrome.once('error',reject);chrome.stderr.on('data',c=>{data+=c;const match=data.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match){clearTimeout(timer);resolve(match[1]);}});});
 ws=new WebSocket(endpoint);await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
 let seq=0;const pending=new Map();
 const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method));},30000);pending.set(id,[v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)}]);ws.send(JSON.stringify({id,method,params,sessionId}));});
 ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const [resolve,reject]=pending.get(m.id);pending.delete(m.id);m.error?reject(Error(JSON.stringify(m.error))):resolve(m.result);}
  if(m.method==='Network.loadingFailed' && m.params.canceled)canceledRequests.add(m.sessionId+':'+m.params.requestId);
  if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);
  if(m.method==='Log.entryAdded' && m.params.entry.level==='error')errors.push(m.params.entry);
  if(m.method==='Runtime.bindingCalled' && m.params.name==='r266CSP')violations.push(JSON.parse(m.params.payload));
  if(m.method==='Fetch.requestPaused')void (async()=>{const url=m.params.request.url,pathname=new URL(url).pathname,id=m.params.requestId;
   if(pathname==='/api/image' || pathname==='/api/champion-asset'){await send('Fetch.fulfillRequest',{requestId:id,responseCode:200,responseHeaders:[{name:'Content-Type',value:'image/svg+xml'}],body:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="640" height="360"><rect width="640" height="360" fill="#23384a"/><circle cx="320" cy="180" r="80" fill="#cc9e45"/></svg>').toString('base64')},m.sessionId);}
   else if(['/app.js','/gameplay.js','/history-filters.js','/gameplay.css'].includes(pathname)){let body=process.env.R266_WEB_OVERRIDE && fs.existsSync(path.join(process.env.R266_WEB_OVERRIDE,pathname))?fs.readFileSync(path.join(process.env.R266_WEB_OVERRIDE,pathname),'utf8'):await (await fetch(ready.baseUrl+pathname)).text();if(pathname==='/app.js')body=body.replace(/\}\)\(\);\s*$/, 'window.__r266App={state,renderItems};})();');if(pathname==='/gameplay.js')body=body.replace(/\}\)\(\);\s*$/, 'window.__r266Game={state,loadOverview};})();');await send('Fetch.fulfillRequest',{requestId:id,responseCode:200,responseHeaders:[{name:'Content-Type',value:pathname.endsWith('.css')?'text/css':'text/javascript'}],body:Buffer.from(body).toString('base64')},m.sessionId);}
   else if(pathname==='/demo-data.js'){const response=await fetch(ready.baseUrl+pathname),body=(await response.text()).replace('  const fixtures = new Map([',(process.env.R266_CARD_SERVER?'overview.matches=source=overview.matches.slice(0,5);'.replace('source=',''):inject)+'\n  const fixtures = new Map([').replace('    const params = new URLSearchParams(url.split("?")[1] || "");','    const params = new URLSearchParams(url.split("?")[1] || "");'+(process.env.R266_CARD_SERVER?`if(pathname==='/api/gameplay/overview' && init?.method==='POST' && window.__r266TimingStarted)return nativeFetch(pathname,{...init,method:'POST',body:JSON.stringify({gameName:'Fixture',tagLine:'KR1',region:'kr',count:5})});if(pathname==='/api/gameplay/season-summary')return window.__r266TimingStarted?nativeFetch(input,init):Promise.resolve(new Response('{}',{headers:{'Content-Type':'application/json'}}));`:intercept));await send('Fetch.fulfillRequest',{requestId:id,responseCode:200,responseHeaders:[{name:'Content-Type',value:'text/javascript'}],body:Buffer.from(body).toString('base64')},m.sessionId);}
   else if(process.env.R266_CARD_SERVER && pathname.startsWith('/api/') && !['/api/gameplay/overview','/api/gameplay/season-summary'].includes(pathname))await send('Fetch.fulfillRequest',{requestId:id,responseCode:200,responseHeaders:[{name:'Content-Type',value:'application/json'}],body:Buffer.from('{}').toString('base64')},m.sessionId);
   else if(url.startsWith(ready.baseUrl+'/'))await send('Fetch.continueRequest',{requestId:id},m.sessionId);
   else await send('Fetch.failRequest',{requestId:id,errorReason:'BlockedByClient'},m.sessionId);
  })().catch(async e=>{if(closedSessions.has(m.sessionId))return;if(e.message.includes('Invalid InterceptionId')){await new Promise(resolve=>setTimeout(resolve,50));if(canceledRequests.has(m.sessionId+':'+m.params.networkId)){canceledInterceptions++;return;}}errors.push({message:e.message});});
 });
 for(const theme of (process.env.R266_CASE_ONE || process.env.R266_CARD_SERVER?['dark']:['dark','light']))for(const width of (process.env.R266_MATRIX || process.env.R266_CASE_ONE || process.env.R266_CARD_SERVER?[1440]:[1920,1440,1280,900])){
  const storage='empty',height=width===900?760:900;
  const {targetId}=await send('Target.createTarget',{url:'about:blank'}),{sessionId}=await send('Target.attachToTarget',{targetId,flatten:true}),call=(m,p)=>send(m,p,sessionId);
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  const until=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await new Promise(resolve=>setTimeout(resolve,50));}const snapshot=await evaluate("({api:window.__r266API?.slice(-20),statuses:window.__r266Statuses?.slice(-10),ensureCalls:window.__r266EnsureCalls,conflict:window.__r266Conflict,hidden:document.hidden,view:document.querySelector('#favorites-panel')?.textContent.slice(0,1200),grid:document.querySelector('#skin-grid')?.textContent.slice(0,500),launch:document.querySelector('#client-launchpad')?.hidden,filter:!!document.querySelector('[data-af-open]'),timingState:window.__r266Game && {section:__r266Game.state.section,tabs:__r266Game.state.tabs.map(t=>({key:t.key,loading:t.loading,matches:t.data?.matches?.length,error:t.error}))},requests:window.__r266OverviewRequests,modal:document.querySelector('[data-af-menu]')?.outerHTML.slice(0,200),menu:document.querySelector('#overview-content')?._afBoundTab?.advancedMenu,overview:document.querySelector('#overview-content')?._overviewViewTab && {loading:document.querySelector('#overview-content')._overviewViewTab.loading,error:document.querySelector('#overview-content')._overviewViewTab.initialPageError}})");throw Error('timeout '+expression+' '+JSON.stringify(snapshot));};
  const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
  const shot=async name=>{if(storage!=='empty')return;const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,`${theme}-${name}.png`),Buffer.from(r.data,'base64'));};
  await send('Target.activateTarget',{targetId});
  await call('Network.enable');await call('Page.enable');await call('Runtime.enable');await call('Log.enable');await call('Runtime.addBinding',{name:'r266CSP'});
  const values=storage==='saved'?saved:storage==='malformed'?{...saved,'deep-legends-history-presets-v1':'[{"name":"bad","conditions":42}]','lol-loot-player-tab-order':'{"bad":1}','lol-loot-default-match-filter':'wrong'}:{};
  await call('Page.addScriptToEvaluateOnNewDocument',{source:`window.__r266CardEvents=[];(()=>{let report;Object.defineProperty(window,'reportFlowDiagnostic',{configurable:true,get(){return report},set(fn){report=function(...args){if(args[0]==='overview_card_ready')__r266CardEvents.push(args[2]);return fn?.(...args)}}});})();window.__r266OverlayShown=0;new MutationObserver(events=>{for(const e of events)if(e.target.id==='startup-loading' && !e.target.hidden)window.__r266OverlayShown++;}).observe(document,{subtree:true,attributes:true,attributeFilter:['hidden']});window.__r266Streams=[];window.EventSource=class {constructor(){window.__r266Streams.push(this)}addEventListener(){}close(){}};try{localStorage.clear();for(const [k,v] of Object.entries(${JSON.stringify({...values,'lol-loot-theme':theme})}))localStorage.setItem(k,v);}catch{};document.addEventListener('securitypolicyviolation',e=>r266CSP(JSON.stringify({directive:e.effectiveDirective,blockedURI:e.blockedURI})));`});
  await call('Fetch.enable',{patterns:[{urlPattern:'*'}]});await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});
  await call('Network.setCookie',{name:'lol_loot_token',value:ready.token,url:ready.baseUrl,httpOnly:true});
  await call('Page.navigate',{url:ready.baseUrl+'/?demo&section=overview'+(process.env.R266_MATRIX?'&matrix':'')});
  if(process.env.R266_CARD_SERVER)await until("!!window.__r266Game && !!document.querySelector('#setting-default-page')");else {await until("document.querySelector('.match-list .match-entry')");await until("!document.querySelector('#overview-content')._overviewViewTab.loading");}await evaluate(`document.documentElement.dataset.theme='${theme}'`);
  if(process.env.R266_CARD_SERVER){await evaluate("window.__r266CardEvents=[];window.__r266TimingStarted=true;window.dispatchEvent(new CustomEvent('deep-legends:open-player',{detail:{gameName:'Fixture',tagLine:'KR1',region:'kr',source:'pro-players',proPlayer:{playerName:'Rookie',teamCode:'IG'}}}));");await until("document.querySelector('#overview-content')._overviewViewTab?.group==='pro' && document.querySelector('.match-list .match-entry')");await until("document.querySelector('#overview-content')._overviewViewTab?.opggSeason?.data && document.querySelector('.career-column').textContent.includes('杰斯')");const cardEvidence=await evaluate("({events:__r266CardEvents,opggDOMReadyMs:Math.round(performance.now()-document.querySelector('#overview-content')._overviewViewTab.overviewCardLoad.startedAt),opggGames:document.querySelector('#overview-content')._overviewViewTab.opggSeason.data.overall.games})");for(const card of ['ranks','masteries','positions'])assert(cardEvidence.events.some(e=>e.card===card),JSON.stringify(cardEvidence));assert.equal(cardEvidence.opggGames,573);results.push(cardEvidence);await shot('p7-cards');closedSessions.add(sessionId);await send('Target.closeTarget',{targetId});break;}
  if(process.env.R266_MATRIX) {
    for(const w of [900,1100,1280,1440,1600,1920])for(const zoom of [.9,1,1.1,1.25,'auto']) {
      await call('Emulation.setDeviceMetricsOverride',{width:w,height:900,deviceScaleFactor:1,mobile:false});await evaluate(`(()=>{const input=document.getElementById('setting-ui-scale');input.value='${zoom}';input.dispatchEvent(new Event('change',{bubbles:true}));})()`);await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
      const scale=await evaluate("({selected:document.getElementById('setting-ui-scale').value,root:Number(getComputedStyle(document.documentElement).getPropertyValue('--ui-zoom')),frame:Number(getComputedStyle(document.querySelector('.app-frame')).zoom)})");assert.equal(scale.selected,String(zoom));assert.equal(scale.root,zoom==='auto'?1:zoom);assert.equal(scale.frame,scale.root);
      assert.deepEqual(await evaluate("document.querySelector('#overview-content')._overviewViewTab.data.matches.map(m=>m.modeGroup)"),['solo','hextech-aram','arena']);const rects=await evaluate(`(()=>{const selectors=['.match-champion > .game-icon','.match-loadout-mini','.match-kda','.match-stats','.match-players','.match-actions'];return [...document.querySelectorAll('.match-summary')].slice(0,12).map(n=>({mode:n.className,gameId:n.closest('.match-entry').dataset.matchId,blocks:selectors.map(s=>{const el=n.querySelector(s),r=el?.getBoundingClientRect();return {selector:s,visible:!!el && getComputedStyle(el).display!=='none' && r.width>0 && r.height>0 && el.getClientRects().length>0,width:r?.width,height:r?.height,left:r?.left,right:r?.right,top:r?.top,bottom:r?.bottom}})}))})()`);
      const overlaps=[];for(const card of rects)for(let i=0;i<card.blocks.length;i++)for(let j=i+1;j<card.blocks.length;j++){const a=card.blocks[i],b=card.blocks[j];if(a.visible && b.visible && Math.min(a.right,b.right)-Math.max(a.left,b.left)>.5 && Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>.5)overlaps.push({mode:card.mode,a:a.selector,b:b.selector});}
      assert.equal(rects.length,3,'matrix requires all three modes');for(const card of rects)for(const selector of ['.match-champion > .game-icon','.match-loadout-mini','.match-kda','.match-actions'])assert(card.blocks.find(b=>b.selector===selector)?.visible,JSON.stringify({theme,w,zoom,card,missing:selector}));if(!process.env.R266_MATRIX_BASELINE)assert.equal(overlaps.length,0,JSON.stringify({theme,w,zoom,overlaps}));await shot('p5-'+w+'-'+zoom);results.push({theme,w,zoom,scale,overlaps,rects});
    }
    closedSessions.add(sessionId);await send('Target.closeTarget',{targetId});break;
  }
  await click('.match-filterbar [data-history-filter-load],.match-filterbar [data-af-open]');await until("document.querySelector('[data-af-menu]')?.open");await click('[data-af-category="hero"]');
  const dialog=await evaluate("(()=>{const r=document.querySelector('[data-af-menu]').getBoundingClientRect();return {left:r.left,top:r.top,width:r.width,height:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2}})()");assert(Math.abs(dialog.cx-width/2)<1 && Math.abs(dialog.cy-height/2)<1,JSON.stringify(dialog));
  assert.deepEqual(await evaluate("[...document.querySelectorAll('[data-af-page]')].map(n=>n.textContent)"),['条件','常用']);
  await evaluate("window.__r266Tasks=[];new PerformanceObserver(list=>__r266Tasks.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask'});window.__r266ListMutations=0;new MutationObserver(records=>__r266ListMutations+=records.length).observe(document.querySelector('.match-list'),{childList:true,subtree:true});window.__r266Options=[...document.querySelectorAll('[data-af-option]')];window.__r266Images=__r266Options.map(n=>n.querySelector('img'));window.__r266ClickStart=performance.now()");
  await click('[data-af-option="103"]');await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  assert.equal(await evaluate('__r266ListMutations'),0);const clickTasks=await evaluate('__r266Tasks.filter(t=>t.start>=__r266ClickStart).reduce((n,t)=>n+t.duration,0)');assert(clickTasks<=100,'click long tasks '+clickTasks);
  for(const id of [238,157,875,145])await click('[data-af-option="'+id+'"]');assert.equal(await evaluate('__r266ListMutations'),0);for(const id of [157,875,145])await click('[data-af-option="'+id+'"]');
  for(let batch=0;batch<3;batch++)await evaluate("(()=>{const container=document.getElementById('overview-content'),tab=container._afBoundTab,ctx=container._afContext();tab.data.matches=[...tab.data.matches,...Array.from({length:20},(_,i)=>({...tab.data.matches[4],gameId:1000000+"+batch+"*20+i}))];tab.data.pagination.count+=20;tab.nextBegIndex=tab.data.pagination.count;ctx.progress();return true})()");
  assert(await evaluate("document.querySelector('[data-af-preview]').textContent.includes('已查 1060 场')"),'progress cursor must update '+await evaluate("document.querySelector('[data-af-preview]').textContent"));
  assert(await evaluate("__r266Options.every((n,i)=>n===document.querySelectorAll('[data-af-option]')[i] && n.querySelector('img')===__r266Images[i])"),await evaluate("JSON.stringify({before:__r266Options.map(n=>({id:n.dataset.afOption,connected:n.isConnected})),after:[...document.querySelectorAll('[data-af-option]')].map(n=>n.dataset.afOption),loading:document.getElementById('overview-content')._afBoundTab.loading})"));
  await evaluate("document.querySelector('.af-options.is-hero').scrollTop=100000");await until("[...document.querySelectorAll('.af-options.is-hero img')].every(img=>{const r=img.getBoundingClientRect(),p=img.closest('.af-options').getBoundingClientRect();return r.top>=p.bottom || r.bottom<=p.top || img.complete && img.naturalWidth>0})");await evaluate("document.querySelector('.af-options.is-hero').scrollTop=0");
  await until("[...document.querySelectorAll('.af-options.is-hero img')].every(img=>{const r=img.getBoundingClientRect(),p=img.closest('.af-options').getBoundingClientRect();return r.top>=p.bottom || r.bottom<=p.top || img.complete && img.naturalWidth>0})");await evaluate("(()=>{const c=document.getElementById('overview-content'),t=c._afBoundTab;window.__r266ShotDraft=t.advancedMenu.conditions;t.advancedMenu.conditions={...__r266ShotDraft,result:{values:['loss'],not:true},performance:{values:['mvp'],thresholds:{kda:3},not:false}};deepLegendsHistoryFilters.refresh(c,t,c._afContext());})()");assert(await evaluate("[...document.querySelectorAll('.af-options.is-hero .game-icon')].every(n=>{const r=n.getBoundingClientRect();return Math.abs(r.height-48)<1 && Math.abs(r.width-48)<1})"),'hero avatars must stay square');await shot('p1-hero-'+width);await evaluate("(()=>{const c=document.getElementById('overview-content'),t=c._afBoundTab;t.advancedMenu.conditions=__r266ShotDraft;deepLegendsHistoryFilters.refresh(c,t,c._afContext());})()");if(width===1440){await evaluate("window.__r266DraftBefore=document.getElementById('overview-content')._afBoundTab.advancedMenu.conditions");await click('[data-af-category="performance"]');await click('[data-af-option="mvp"]');await evaluate("(()=>{const n=document.querySelector('[data-af-threshold=kda]');n.value='3';n.dispatchEvent(new Event('change',{bubbles:true}));})()");await shot('p1-performance');await evaluate("localStorage.setItem('deep-legends-history-presets-v1',JSON.stringify([{name:'排位上分',conditions:{result:{values:['win'],not:false},hero:{values:['103','238'],not:false}}},{name:'表现亮眼',conditions:{performance:{values:['mvp'],thresholds:{kda:3},not:false}}},{name:'和朋友一起',conditions:{hero:{values:['157'],not:false}}}]))");await click('[data-af-page="saved"]');await click('[data-af-rename="2"]');assert(await evaluate("document.querySelector('[data-af-menu]').getBoundingClientRect().height<=640"),'saved dialog height');await shot('p1-saved');await evaluate("document.getElementById('overview-content')._afBoundTab.advancedMenu.conditions=__r266DraftBefore");await click('[data-af-page="conditions"]');await click('[data-af-category="hero"]');}
  await evaluate('__r266CloseStart=performance.now()');await click('[data-af-close]');await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
  assert(await evaluate("document.activeElement===document.querySelector('[data-af-open]')"),await evaluate("JSON.stringify({active:document.activeElement.outerHTML,menu:document.querySelector('[data-af-menu]').outerHTML.slice(0,200)})"));
  const metrics=await evaluate("({nodes:document.querySelectorAll('*').length,images:document.querySelectorAll('img').length,tasks:__r266Tasks.filter(t=>t.start>=__r266CloseStart)})");const total=metrics.tasks.reduce((n,t)=>n+t.duration,0),max=Math.max(0,...metrics.tasks.map(t=>t.duration));assert(metrics.nodes<=15000 && metrics.images<=1500,JSON.stringify(metrics));assert(total<=300 && max<=200,JSON.stringify(metrics));assert.equal(await evaluate("document.querySelectorAll('.match-list > .match-entry').length"),20);
  await click('[data-af-open]');await evaluate("document.querySelector('[data-af-menu]').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");assert(await evaluate("!document.querySelector('[data-af-menu]').open && document.activeElement===document.querySelector('[data-af-open]')"));
  await click('[data-af-open]');await call('Input.dispatchMouseEvent',{type:'mousePressed',x:4,y:4,button:'left',clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:4,y:4,button:'left',clickCount:1});assert(await evaluate("!document.querySelector('[data-af-menu]').open"),'backdrop did not close');
  await evaluate('window.__r266CycleStart=performance.now()');
  for(const id of [103,238,157,875,145]) {await click('[data-af-open]');await click('[data-af-clear]');await click('[data-af-category="hero"]');await click('[data-af-option="'+id+'"]');await click('[data-af-close]');await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');}
  const cycleTasks=await evaluate('__r266Tasks.filter(t=>t.start>=__r266CycleStart).reduce((n,t)=>n+t.duration,0)');assert(cycleTasks<=1000,'five filter cycles long tasks '+cycleTasks);
  if(width===1440 && (!process.env.R266_CASE_ONE || process.env.R266_EXTRAS)){
    await click('#section-settings');await click('#settings-tab-privacy');await until("document.querySelector('[data-riot-cache-clear]')?.getBoundingClientRect().height>0");
    const settings=await evaluate(`(()=>{const cache=document.querySelector('.setting-cache-card'),button=cache.querySelector('button'),title=cache.querySelector('h3'),privacy=document.querySelector('#setting-mask-names').closest('.setting-card'),previous=document.getElementById('setting-riot-key-clear'),r=n=>{const v=n.getBoundingClientRect();return {top:v.top,height:v.height,right:v.right,cy:v.top+v.height/2}};return {cache:r(cache),button:r(button),title:r(title),privacy:r(privacy),previous:r(previous)}})()`);
    assert(settings.cache.height>0 && settings.button.height>0 && settings.privacy.height>0,'settings row must be visible');assert(Math.abs(settings.title.cy-settings.button.cy)<=2,JSON.stringify(settings));assert(Math.abs(settings.cache.height-settings.privacy.height)<=2,JSON.stringify(settings));assert(Math.abs(settings.button.right-settings.previous.right)<=1,JSON.stringify(settings));await shot('p6-settings');
    await click('[data-riot-cache-clear]');await until("document.querySelector('.setting-cache-card [role=status]').textContent");const statusButton=await evaluate("(()=>{const r=document.querySelector('[data-riot-cache-clear]').getBoundingClientRect();return {cy:r.top+r.height/2,right:r.right}})()");assert(Math.abs(statusButton.cy-settings.button.cy)<=1 && Math.abs(statusButton.right-settings.button.right)<=1,JSON.stringify(statusButton));await until("document.querySelector('.setting-cache-card [role=status]').hidden");
    await click('#section-favorites');await click('[data-favorites-page="collection"]');await until("window.__r266App?.state.items?.length");
    const firstCount=await evaluate(`(()=>{const a=__r266App;window.__r266CollectionTasks=[];new PerformanceObserver(l=>__r266CollectionTasks.push(...l.getEntries().map(e=>e.duration))).observe({type:'longtask'});const firstStarted=performance.now();a.state.items=Array.from({length:1192},(_,i)=>({...a.state.items[i%a.state.items.length],id:100000+i,name:'收藏夹具 '+i,owned:true}));a.state.view='owned';a.state.loading=false;a.state.status.snapshotReady=true;a.renderItems();return {count:document.querySelector('#skin-grid').children.length,ms:performance.now()-firstStarted}})()`);assert.equal(firstCount.count,40);assert(firstCount.ms<=300,'collection first screen '+firstCount.ms);await until("document.querySelector('#skin-grid').children.length===1192");await evaluate('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');const collectionMax=await evaluate('Math.max(0,...__r266CollectionTasks)');assert(collectionMax<=200,'collection long task '+collectionMax);
    const samples=[];for(const kind of ['matches','zero']){
      await call('Page.navigate',{url:ready.baseUrl+'/?demo&section=overview&loading='+kind});await until("document.querySelector('.match-skeleton')");await evaluate(`document.documentElement.dataset.theme='${theme}'`);
      for(const at of [0,500,1000,1400]){await until('performance.now()-__r266HeaderAt>='+at);const sample=await evaluate("(()=>{const hero=document.querySelector('.champion-performance');return {at:Math.round(performance.now()-__r266HeaderAt),skeletons:document.querySelectorAll('.match-skeleton').length,left:document.querySelectorAll('.career-pending').length,text:document.querySelector('#overview-content').textContent,hero:{text:hero.textContent,bars:hero.querySelectorAll('.career-pending.gameplay-skeleton span').length,rows:hero.querySelectorAll('.champion-stat-row').length}}})()");assert(sample.hero.bars>=2 && sample.hero.rows===0,'hero statistics must stay pending '+JSON.stringify(sample));assert(!/已统计 0 场|暂无英雄统计|—:1 KDA|全部英雄/.test(sample.hero.text),JSON.stringify(sample));assert.equal(sample.skeletons,5);assert.equal(sample.left,6);assert(!/没有符合条件的对局|共 0 场|战绩未读全/.test(sample.text),JSON.stringify(sample));samples.push({kind,at:sample.at,skeletons:sample.skeletons,left:sample.left,hero:sample.hero});if(kind==='matches' && at===500)await shot('p3-loading-pending');}
      if(kind==='matches')await until("document.querySelector('.match-list .match-entry')");else await until("document.querySelector('#overview-content').textContent.includes('没有符合条件的对局')");assert(await evaluate("!document.querySelector('.match-skeleton,.career-pending') && !document.querySelector('#overview-content')._overviewViewTab.loading"),'final stream must clear pending state and skeletons');if(kind==='matches')await shot('p3-loading-complete');
      await until('performance.now()-__r266HeaderAt>=1600');const complete=await evaluate("(()=>{const hero=document.querySelector('.champion-performance'),tab=document.querySelector('#overview-content')._overviewViewTab;return {at:Math.round(performance.now()-__r266HeaderAt),text:hero.textContent,pending:!!hero.querySelector('.career-pending'),rows:hero.querySelectorAll('.champion-stat-row:not(.is-overall)').length,games:tab.data.seasonOverall.games,complete:tab.data.seasonStatsProgress.complete}})()");assert(!complete.pending && complete.complete,JSON.stringify(complete));if(kind==='zero')assert(complete.games===0 && complete.text.includes('暂无英雄统计'),JSON.stringify(complete));else assert(complete.games>0 && complete.rows>0 && !complete.text.includes('暂无英雄统计'),JSON.stringify(complete));samples.push({kind,completed:complete});
    }
    results.push({theme,width,settings,collectionFirst:firstCount.count,collectionFirstMs:firstCount.ms,collectionCards:1192,collectionLongestMs:collectionMax,pendingSamples:samples});
  }
  results.push({theme,width,dialog,cycleLongTasksMs:cycleTasks,clickLongTasksMs:clickTasks,applyLongTasksMs:total,applyLongestMs:max,...metrics});
  closedSessions.add(sessionId);await send('Target.closeTarget',{targetId});
 }
 assert.equal(violations.length,0,JSON.stringify(violations));assert.equal(errors.length,0,JSON.stringify(errors));
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({host:{platform:process.platform,arch:process.arch,node:process.version},completedAt:new Date().toISOString(),scope:process.env.R266_CARD_SERVER?'real Chromium + actual overview/OP.GG Go handlers and embedded assets; identical fake upstreams; no production binary/Windows/real latency claim':'real Chromium on recorded host; public production binary/CSP; synthetic API data; no Windows/real LCU claim',csp,results,errors,violations,canceledInterceptions},null,2));
 console.log(JSON.stringify({cases:results.length,errors:errors.length,violations:violations.length}));
}
start().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.message,results,errors,violations},null,2));console.error(e);process.exitCode=1;}).finally(()=>{ws?.close();chrome?.kill();backend?.kill();setTimeout(()=>fs.rmSync(temp,{recursive:true,force:true,maxRetries:8,retryDelay:100}),250).unref();});
