"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {JSDOM}=require(require.resolve("jsdom",{paths:[path.join(__dirname,"../../desktop")]}));
const source=fs.readFileSync(path.join(__dirname,"suite.js"),"utf8");
function fn(name){const start=source.indexOf(`function ${name}(`),body=source.indexOf("{",source.indexOf(")",start));let depth=0,quote="",escape=false;for(let i=body;i<source.length;i++){const c=source[i];if(quote){if(escape)escape=false;else if(c==="\\")escape=true;else if(c===quote)quote="";continue;}if(['"',"'","`"].includes(c)){quote=c;continue;}if(c==="{")depth++;if(c==="}"&&--depth===0)return source.slice(start,i+1);}throw Error(name);}
function harness(respond){const dom=new JSDOM('<div id="rig"></div>'),state={rig:{connected:false}},requests=[],messages=[],root=dom.window.document.getElementById("rig");const deps={state,metrics:{rig:{}},roots:{rig:root},checked:v=>v?' checked':'',escapeHTML:v=>String(v||""),rigLockIcon:()=>"",maintenanceActions:[],api:async(url,opts)=>{requests.push([url,JSON.parse(opts.body)]);return respond?.(url,opts);},toast:v=>messages.push(v),runRigRequest(){},requestConfirmation(){}};const helpers=Function(...Object.keys(deps),fn("renderRig")+fn("bindRigControls")+";return {renderRig,bindRigControls};")(...Object.values(deps));return {dom,state,root,requests,messages,...helpers};}
test("R186 game settings toggle defaults on in existing lock area and renders persisted off",()=>{const h=harness();try{h.renderRig();let input=h.root.querySelector('[data-rig-settings-sync]');assert.equal(input.checked,true);assert.equal(input.closest('section').querySelector('h3').textContent,'安装与连接');h.state.rig.keepGameSettings=false;h.renderRig();assert.equal(h.root.querySelector('[data-rig-settings-sync]').checked,false);}finally{h.dom.window.close();}});
test("R186 toggle sends only its preference and retains successful value across render",async()=>{const h=harness();try{h.renderRig();const input=h.root.querySelector('[data-rig-settings-sync]');input.checked=false;input.dispatchEvent(new h.dom.window.Event('change'));assert.equal(input.disabled,true);await new Promise(setImmediate);assert.deepEqual(h.requests,[['/api/rig/settings-sync',{enabled:false}]]);assert.equal(h.state.rig.keepGameSettings,false);h.renderRig();assert.equal(h.root.querySelector('[data-rig-settings-sync]').checked,false);}finally{h.dom.window.close();}});
test("R186 failed preference write restores switch and shows failure",async()=>{const h=harness(()=>{throw Error('保存失败')});try{h.renderRig();const input=h.root.querySelector('[data-rig-settings-sync]');input.checked=false;input.dispatchEvent(new h.dom.window.Event('change'));await new Promise(setImmediate);assert.equal(input.checked,true);assert.equal(input.disabled,false);assert.deepEqual(h.messages,['保存失败']);assert.equal(h.state.rig.keepGameSettings,undefined);}finally{h.dom.window.close();}});
