'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('../../desktop/node_modules/jsdom');const {compile,escapeHTML}=require('./r188-harness.cjs');
const source=fs.readFileSync(`${__dirname}/gameplay.js`,'utf8'),payload=require('../testdata/r197-post-game-reveal.json');
function render(player){const deps={state:{settings:{maskNames:false}},escapeHTML,liveDisplayedChampionId:p=>p.championId,iconFigure:()=>'<img alt="赛娜">',rankTitle:()=> '黄金 I',renderLivePremadeTag:()=>'',proBadgeAttributes:()=>'',renderProIdentityBadge:()=>'',number:String,percent:n=>`${n}%`,kda:String};return compile(source,['renderLivePlayer','renderInsightMatches','liveHistoryStateOf','liveHistorySettled','champSelectEnemyPlaceholder','positionLabel','maskedPlayerName','playerLabel'],deps).renderLivePlayer(player,9)}
test('R197 8 actual post-game payload replaces hidden card with name/rank and clickable overview reference',()=>{const before=payload.before.players[9],after=payload.after.players[9];assert.equal(before.hidden,true);assert.equal(after.hidden,false);assert.ok(after.rank);const dom=new JSDOM(render(after));try{assert.match(dom.window.document.body.textContent,/Fixture9/);assert.match(dom.window.document.body.textContent,/黄金 I/);assert.doesNotMatch(dom.window.document.body.textContent,/隐藏玩家|客户端未公开该玩家/);const name=dom.window.document.querySelector('[data-player-ref]');assert.ok(name);assert.equal(name.getAttribute('data-player-ref'),after.playerRef);assert.equal(name.disabled,false)}finally{dom.window.close()}});
test('R197 9 participant still hidden retains R193 card exactly',()=>{const dom=new JSDOM(render(payload.before.players[9]));try{assert.match(dom.window.document.body.textContent,/隐藏玩家/);assert.equal(dom.window.document.body.textContent.split('客户端未公开该玩家').length-1,1);assert.doesNotMatch(dom.window.document.body.textContent,/黄金 I|未定级/);assert.equal(dom.window.document.querySelector('[data-player-ref]'),null);assert.equal(dom.window.document.querySelector('.live-player-copy button').disabled,true)}finally{dom.window.close()}});
test('R197 post-game SSE bridge refreshes retained live snapshot only outside active phases',()=>{const app=fs.readFileSync(`${__dirname}/app.js`,'utf8');assert.match(app,/event\.data === "live-post-game-reveal"[\s\S]*?deep-legends:post-game-reveal/);const marker='window.addEventListener("deep-legends:post-game-reveal", () => {';const start=source.indexOf(marker),end=source.indexOf('\n  });',start);assert.ok(start>=0&&end>start);const block=source.slice(start,end+6);let handler,calls=[];const state={section:'live',live:{gameId:197},beacon:{phase:'EndOfGame'}};Function('window','state','liveGamePhase','queueLiveEventRefresh',block)({addEventListener(_name,fn){handler=fn}},state,p=>['ChampSelect','GameStart','InProgress','Reconnect'].includes(p),(...args)=>calls.push(args));handler();assert.deepEqual(calls,[['event']]);for(const phase of ['InProgress','Reconnect','ChampSelect']){state.beacon.phase=phase;handler()}assert.equal(calls.length,1);state.beacon.phase='EndOfGame';state.section='overview';handler();assert.equal(calls.length,1)});
module.exports={render};

test('R197 reveal event during an active roster request leaves a trailing refresh queued',()=>{const state={destroyed:false,section:'live',beacon:{phase:'EndOfGame'},liveLoading:true,liveRefreshQueued:false,livePhaseRefreshQueued:false,liveEventTimer:0};const queue=compile(source,['queueLiveEventRefresh'],{state,connected:()=>true,document:{hidden:false},liveGamePhase:()=>false,recordLiveRefresh(){},setTimeout(){throw Error('must wait for active load finalizer')},loadLive(){throw Error('must not overlap loads')}}).queueLiveEventRefresh;queue('event');assert.equal(state.liveRefreshQueued,true);assert.equal(state.liveEventTimer,0);assert.match(source,/if \(state\.liveRefreshQueued\) queueLiveEventRefresh\("event"/)});
