'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require('../../desktop/node_modules/jsdom');
const {compile,escapeHTML}=require('./r188-harness.cjs');
const source=fs.readFileSync(process.env.R198_SOURCE_FILE||`${__dirname}/suite.js`,'utf8');
function rig(saved={},respond){const dom=new JSDOM('<div id="rig"></div>'),root=dom.window.document.getElementById('rig');const state={rig:{connected:false,...saved},eventStream:false},requests=[],messages=[];const deps={state,roots:{rig:root},metrics:{rig:{}},escapeHTML,checked:v=>v?' checked':'',rigLockIcon:()=>'',api:async(url,opts)=>{const body=JSON.parse(opts.body);requests.push([url,body]);if(respond)return respond(url,body);saved.cameraMode=body.mode;return {cameraMode:body.mode}},toast:m=>messages.push(m),runRigRequest(){},requestConfirmation(){}};return {dom,root,state,requests,messages,...compile(source,['renderRig','bindRigControls'],deps)}}
test('R198 maintenance camera options default none, save immediately and survive refresh',async()=>{const saved={settingsLocked:true};let h=rig(saved);try{h.renderRig();const select=h.root.querySelector('[data-rig-camera-mode]');assert.equal(select.getAttribute('aria-label'),'进入游戏时的镜头模式');assert.deepEqual([...select.options].map(o=>[o.value,o.textContent]),[['none','不修改'],['free','自由镜头'],['dynamic','动态镜头'],['locked','锁定镜头']]);assert.equal(select.value,'none');assert.equal(select.disabled,false);assert.equal(select.closest('aside').querySelector('h3').textContent,'客户端维护');assert.ok(select.closest('.rig-actions'));assert.equal(h.root.querySelector('[data-rig-settings-sync]'),null);assert.doesNotMatch(h.root.textContent,/保留对局内设置改动/);select.value='free';select.dispatchEvent(new h.dom.window.Event('change'));assert.equal(select.disabled,true);await new Promise(setImmediate);assert.deepEqual(h.requests,[['/api/rig/camera-mode',{mode:'free'}]]);assert.equal(h.state.rig.cameraMode,'free');h.renderRig();assert.equal(h.root.querySelector('select').value,'free')}finally{h.dom.window.close()}h=rig(saved);try{h.renderRig();assert.equal(h.root.querySelector('select').value,'free')}finally{h.dom.window.close()}});
test('R198 failed preference save rolls back without changing previous choice',async()=>{const h=rig({cameraMode:'dynamic'},()=>{throw Error('保存失败')});try{h.renderRig();const select=h.root.querySelector('select');select.value='locked';select.dispatchEvent(new h.dom.window.Event('change'));await new Promise(setImmediate);assert.equal(select.value,'dynamic');assert.equal(select.disabled,false);assert.equal(h.state.rig.cameraMode,'dynamic');assert.deepEqual(h.messages,['保存失败'])}finally{h.dom.window.close()}});
module.exports={rig};
