'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{JSDOM}=require('../../desktop/node_modules/jsdom'),{install,q,qa}=require('./filter-dialog-fixture.cjs');
const af=require(process.env.R269_FILTER_SOURCE || './history-filters.js');
function fixture(){const dom=new JSDOM('<main></main>',{url:'http://fixture'});install(dom);const root=dom.window.document.querySelector('main');const rows=Array.from({length:20},(_,i)=>({gameId:i,result:'win',modeGroup:'solo',createdAt:Date.now(),participants:[{championId:103,championName:'阿狸',position:'top',tripleKills:1,quadraKills:0,pentaKills:0,kills:8,deaths:0,assists:8}]}));const tab={advancedConditions:{},data:{matches:rows,pagination:{hasMore:false}}};let commits=0;const ctx={rows:()=>tab.data.matches,version:()=>tab.data.matches,subject:m=>m.participants[0],tags:()=>[],cursor:()=>20,storage:dom.window.localStorage,container:()=>root,prepare(){},isActive:()=>true,change(){commits++;root.innerHTML=af.render(tab,()=>ctx)+af.renderConditions(tab,()=>ctx);af.bind(root,tab,()=>ctx);}};ctx.change();return {dom,root,tab,ctx,get commits(){return commits;}};}
function verify(h){const {root,tab}=h;if(!tab.advancedMenu?.open)return;const cs=af.normalize(tab.advancedMenu.conditions),category=tab.advancedMenu.category,c=cs[category];for(const node of qa(root,'[data-af-option]'))assert.equal(node.getAttribute('aria-pressed')==='true',Boolean(c?.values.includes(node.dataset.afOption)));for(const node of qa(root,'[data-af-summary]'))assert.equal(Boolean(node.textContent),Boolean(cs[node.dataset.afSummary]));const caps=qa(root,'[data-af-draft-capsules] [data-af-remove]');assert.deepEqual([...caps].map(n=>n.dataset.afRemove).sort(),Object.keys(cs).sort());}
test('R269 fixed zero options remain selectable; all edits share one state through 200 operations',()=>{const h=fixture();q(h.root,'[data-af-open]').click();q(h.root,'[data-af-category="multikill"]').click();assert.deepEqual([...qa(h.root,'[data-af-option]')].map(n=>n.dataset.afOption),['3','4','5']);const five=q(h.root,'[data-af-option="5"]');assert.match(five.textContent,/0 场/);assert.equal(five.disabled,false);five.click();verify(h);q(h.root,'[data-af-close]').click();assert.deepEqual(h.tab.advancedConditions.multikill.values,['5']);assert.match(q(h.root,'[data-af-conditions]').textContent,/五杀/);
 let seed=269;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed;};for(let i=0;i<200;i++){if(!h.tab.advancedMenu.open)q(h.root,'[data-af-open]').click();const category=['result','position','multikill','duration'][random()%4];q(h.root,`[data-af-category="${category}"]`).click();const values=[...qa(h.root,'[data-af-option]')];values[random()%values.length].click();verify(h);if(i%3===0){q(h.root,'[data-af-close]').click();const before=af.normalize(h.tab.advancedConditions);if(i%2===0){const remove=q(h.root,'[data-af-conditions] [data-af-remove]');remove?.click();if(remove)delete before[remove.dataset.afRemove];}q(h.root,'[data-af-open]').click();assert.deepEqual(af.normalize(h.tab.advancedMenu.conditions),before);verify(h);}}
 q(h.root,'[data-af-close]').click();h.dom.window.close();});
test('R269 persistent body dialog survives toolbar replacement and repairs a non-modal open state',()=>{const h=fixture();q(h.root,'[data-af-open]').click();const dialog=h.root._afDialog;assert.equal(dialog.parentNode,h.dom.window.document.body);h.root.innerHTML=af.render(h.tab,()=>h.ctx);af.bind(h.root,h.tab,()=>h.ctx);assert.equal(h.root._afDialog,dialog);assert(dialog.matches(':modal'));dialog._modal=false;af.bind(h.root,h.tab,()=>h.ctx);assert(dialog.matches(':modal'));h.dom.window.close();});
test('R269 stopping aborts immediately, remains visibly stopping until settled, and sends no next page',async()=>{const h=fixture();h.tab.advancedConditions={hero:{values:['999']}};h.tab.data.pagination.hasMore=true;let resolve,requests=0,aborted=0;h.ctx.load=()=>{requests++;return new Promise(r=>resolve=r)};h.ctx.progress=()=>{};const find=af.find(h.tab,h.ctx);af.cancel(h.tab,()=>aborted++);assert(h.tab.advancedSearch.stopping);assert.match(af.counts(h.tab,h.ctx),/正在停止…/);assert.equal(aborted,1);resolve(false);await find;assert.equal(requests,1);assert.equal(h.tab.advancedSearch.running,false);assert.equal(h.tab.advancedSearch.stopReason,'user_stop');assert.equal((af.empty(h.tab,h.ctx).match(/data-af-continue/g)||[]).length,1);assert.equal(af.footer(h.tab,h.ctx),'');h.dom.window.close();});
test('R269 foreign search caps at 100, outage and quota disable the unique entry, quota expires',async()=>{const h=fixture();h.tab.advancedConditions={hero:{values:['999']}};h.tab.data.pagination.hasMore=true;let cursor=0,calls=0;h.ctx.cursor=()=>cursor;h.ctx.foreign=()=>true;h.ctx.progress=()=>{};h.ctx.load=async n=>{calls++;cursor+=n;return true;};await af.find(h.tab,h.ctx);assert.equal(calls,5);assert.equal(h.tab.advancedSearch.scanned,100);cursor=0;calls=0;h.ctx.foreign=()=>false;await af.find(h.tab,h.ctx);assert.equal(calls,15);assert.equal(h.tab.advancedSearch.scanned,300);h.ctx.outage=()=>true;assert.match(af.empty(h.tab,h.ctx),/战绩服务暂时中断/);assert.match(af.empty(h.tab,h.ctx),/data-af-continue disabled/);h.ctx.outage=()=>false;h.ctx.quotaUntil=()=>Date.now()+1000;assert.match(af.empty(h.tab,h.ctx),/查询额度恢复中/);h.ctx.quotaUntil=()=>Date.now()-1;assert.doesNotMatch(af.empty(h.tab,h.ctx),/data-af-continue disabled/);h.tab.data.pagination.hasMore=false;assert.match(af.empty(h.tab,h.ctx),/已查完全部可查询/);h.dom.window.close();});
test('R269 inactive overview binding cannot take the open body dialog from its active owner',()=>{const h=fixture();q(h.root,'[data-af-open]').click();q(h.root,'[data-af-option="win"]').click();const dialog=h.root._afDialog,body=dialog.innerHTML,owner=dialog._afOwner,other=h.dom.window.document.createElement('aside');h.dom.window.document.body.append(other);const tab={advancedConditions:{},data:{matches:h.tab.data.matches}},ctx={...h.ctx,isActive:()=>false,container:()=>other};other.innerHTML=af.render(tab,()=>ctx);af.bind(other,tab,()=>ctx);af.refresh(other,tab,ctx,true);assert.equal(dialog._afOwner,owner);assert.equal(dialog.matches(':modal'),true);assert.equal(dialog.innerHTML,body);q(h.root,'[data-af-close]').click();assert.deepEqual(h.tab.advancedConditions.result.values,['win']);assert.deepEqual(tab.advancedConditions,{});});
