'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const read=f=>fs.readFileSync(path.join(process.env.R88_WEB_ROOT||__dirname,f),'utf8');
function extract(file,name){const s=read(file);let a=s.indexOf(`function ${name}(`);assert.ok(a>=0,name);if(s.slice(a-6,a)==='async ')a-=6;return s.slice(a,s.indexOf('\n  }',a)+4)}
function compile(file,names,deps={}){const c={...deps};vm.runInNewContext(names.map(n=>extract(file,n)).join('\n'),c);return c;}
const settle=()=>new Promise(setImmediate);
function clock(){let now=100000,id=0;const jobs=new Map();return{Date:{now:()=>now},setTimeout:(fn,ms)=>{jobs.set(++id,{fn,at:now+ms});return id;},clearTimeout:i=>jobs.delete(i),advance:async ms=>{now+=ms;for(const [i,j]of [...jobs])if(j.at<=now){jobs.delete(i);j.fn()}await settle();}}}
function live(mutate=s=>s,slow=false){const timer=clock(),posts=[],state={section:'live',beacon:{phase:'ChampSelect'}};const c={...timer,window:{},AbortController,document:{hidden:false},state,connected:()=>true,updateBeacon:p=>state.beacon.phase=p,markOverviewAfterGame(){},invalidateLiveForNewGame(){},normalizeLiveGameId:()=>0,recordLiveObservation(){},renderLive(){},scheduleBeaconPoll(){},loadLive(){},fetch:async(url,o)=>{posts.push(JSON.parse(o.body));if(slow)await new Promise((_,reject)=>o.signal?.addEventListener('abort',()=>reject(Error('timeout'))));return{status:204}}};vm.runInNewContext(mutate(read('runtime.js')),c);vm.runInNewContext(['recordLiveRefresh','queueLiveEventRefresh','handleGameplayPhase'].map(n=>extract('gameplay.js',n)).join('\n'),c);return{c,timer,posts,state};}
test('R88 thirteen ChampSelect events per second cause at most two actual diagnostic POSTs',async()=>{
 const h=live();for(let i=0;i<13;i++){h.state.liveRefreshQueued=false;h.c.handleGameplayPhase('ChampSelect','sse',true);h.c.recordLiveRefresh('load','event');await h.timer.advance(75)}assert.ok(h.posts.length>0&&h.posts.length<=2,h.posts.length);assert.ok(h.posts.every(p=>p.section==='live'));
 const bad=live(s=>s.replace('if (sampled && (sampledPending.size','if (false && (sampledPending.size'));for(let i=0;i<13;i++){bad.c.recordLiveRefresh('phase','sse',i%2===0);await bad.timer.advance(75);bad.c.recordLiveRefresh('load','event',i%2===0)}
 // Remove successful-body dedup too by varying the bounded section/reason payload.
 assert.ok(bad.posts.length>2,'rate limiter mutation must be observable');
});
test('R88 slow sampled diagnostics hold one slot and never retry',async()=>{const h=live(s=>s,true);for(let i=0;i<13;i++){h.c.recordLiveRefresh('phase','sse',true);await h.timer.advance(75)}assert.equal(h.posts.length,1);await h.timer.advance(6000);await h.timer.advance(1000);assert.equal(h.posts.length,1)});
test('R88 local request timing is sampled globally and strips paths and identifiers',async()=>{const h=live();for(let i=0;i<100;i++){h.c.window.reportFlowDiagnostic('local_request_client','complete',{endpoint:'status',startedAt:1700000000000+i,completedAt:1700000000050+i,durationMs:50,httpStatus:200,url:'/secret?token=private'});await h.timer.advance(1)}assert.equal(h.posts.length,1);assert.equal(h.posts[0].startedAt,1700000000000);assert.doesNotMatch(JSON.stringify(h.posts),/secret|private|url/)});
function statusHarness(){const timer=clock(),fatal=[],state={controllers:new Map(),statusDelay:3600000,section:'live',status:{connected:true}},reports=[];const c=compile('app.js',['api','refreshStatus','scheduleStatus'],{...timer,state,window:{reportFlowDiagnostic:(...args)=>reports.push(args)},document:{hidden:false},AbortController,Headers,STATUS_INTERVAL:3600000,showFatal:m=>fatal.push(m),clearDisconnectedClientState(){},updateReadingOverlay(){},renderStatus(){},loadClientInstallations:async()=>{}});return{c,timer,state,fatal,reports};}
test('R88 real status timeout is silent twice, fatal on third, and success resets failures',async()=>{const h=statusHarness();h.c.fetch=(_url,o)=>new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(Error('abort'),{name:'AbortError'}))));for(let i=1;i<=3;i++){const p=h.c.refreshStatus();await h.timer.advance(8000);await p;assert.equal(h.fatal.length,i===3?1:0)}assert.equal(h.reports[0][2].durationMs,8000);assert.equal(h.reports[0][2].errorKind,'timeout');h.c.fetch=async()=>({ok:true,status:200,json:async()=>({connected:true})});await h.c.refreshStatus();assert.equal(h.state.statusFailures,0);h.c.fetch=async()=>{throw Error('network')};await h.c.refreshStatus();assert.equal(h.fatal.length,1);assert.equal(h.state.statusFailures,1)});
test('R88 replaced status requests and explicit abort do not count toward fatal threshold',async()=>{const h=statusHarness();h.c.fetch=(_u,o)=>new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(Object.assign(Error('abort'),{name:'AbortError'}))));const a=h.c.refreshStatus();const b=h.c.refreshStatus();await a;h.state.controllers.get('status').abort();await b;assert.equal(h.state.statusFailures,undefined);assert.equal(h.fatal.length,0)});
test('R88 helper failure label does not blame the League client',()=>{const c=compile('app.js',['showFatal'],{el:{connection:{lastElementChild:{},dataset:{}},notice:{querySelector:()=>null},clientLaunchpad:{}},document:{body:{classList:{add(){}}}},escapeHTML:s=>s,updateWorkspaceAvailability(){},hideReadingOverlay(){}});c.showFatal('本地请求超时，请重试');assert.equal(c.el.connection.lastElementChild.textContent,'本地助手无响应')});
test('R88 arena names omit tags but preserve full tooltips, normal tags and masking',()=>{const names=[{gameName:'同名',tagLine:'111',playerRef:'a'},{gameName:'同名',tagLine:'222',playerRef:'b'}],state={settings:{}};let arena=true;const c=compile('gameplay.js',['renderMatchPlayers'],{state,matchPlayerGroups:()=>({arena,groups:[{players:names}]}),playerParticipantName:(p,i)=>state.settings.maskNames?'玩家 '+i:p.gameName+'#'+p.tagLine,escapeHTML:s=>String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;'),iconFigure:()=>'',arenaGroupLabel:()=>''});const html=c.renderMatchPlayers({});assert.match(html,/data-tooltip="同名#111"/);assert.match(html,/data-tooltip="同名#222"/);assert.equal((html.match(/class="match-player-name">同名<\/span>/g)||[]).length,2);assert.doesNotMatch(html,/data-tooltip-overflow/);arena=false;assert.match(c.renderMatchPlayers({}),/class="match-player-name">同名#111/);state.settings.maskNames=true;arena=true;assert.doesNotMatch(c.renderMatchPlayers({}),/同名|#111/)});
test('R88 OP uses gold badge above source S',()=>{const c=compile('champions.js',['tierBadge','tierDisplay']);assert.match(c.tierBadge(0,'','OP'),/tier-icons\/op.svg.*梯度 OP/);assert.match(c.tierBadge(0,'','S'),/yourgg-s.svg.*梯度 S/)});
test('R88 protected active match-main and match-stats rules remain byte-identical',()=>{const css=read('gameplay.css');const actual=[...css.matchAll(/[^{}\n]+\{[^{}]*\}/g)].map(m=>m[0]).filter(s=>/\.match-(?:main|stats)(?![\w-])/.test(s.split('{')[0]));const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'../testdata/r88/protected-layout-rules.json')));assert.deepEqual(actual,expected)});
