'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'r197198-mutants-'));const live=fs.readFileSync(path.join(root,'backend/live_post_game_reveal.go'),'utf8'),camera=fs.readFileSync(path.join(root,'backend/game_camera_mode.go'),'utf8');
const entries=[
 {name:'position-instead-of-champion',ticket:197,test:'TestR197SennaPostGameReveal',file:'live_post_game_reveal.go',text:live.replace('participant.TeamID == hidden.TeamID && participant.ChampionID == hidden.ChampionID','participant.TeamID == hidden.TeamID && participant.ParticipantID == match.Participants[i].ParticipantID')},
 {name:'reveal-during-game',ticket:197,test:'TestR197InProgressNeverLoadsMatch',file:'live_post_game_reveal.go',text:live.replace('phase == "GameStart" || phase == "InProgress" || phase == "Reconnect" {\n\t\ta.stopPostGameReveal()', 'phase == "GameStart" || phase == "Reconnect" {\n\t\ta.stopPostGameReveal()').replace('if !isEndOfGamePhase(phase) {','if !isEndOfGamePhase(phase) && phase != "InProgress" {')},
 {name:'ambiguous-take-first',ticket:197,test:'TestR197AmbiguousAndHiddenParticipants',file:'live_post_game_reveal.go',text:live.replace('if len(candidates) > 1 {','if false {')},
 {name:'patch-entire-settings',ticket:198,test:'TestR198CameraSingleFieldPatchAndSave',file:'game_camera_mode.go',text:camera.replace('patch := map[string]map[string]any{section: {name: replacement}}','patch := decodeLCUSettings(payload)\n patch[section][name]=replacement')},
 {name:'remarshal-local-json',ticket:198,test:'TestR198CameraFileBytesPreserved',file:'game_camera_mode.go',text:camera.replace('if string(data) == string(next) {','if strings.EqualFold(filepath.Ext(file),".json"){var value any;json.Unmarshal(next,&value);next,_=json.Marshal(value)}\n if string(data) == string(next) {')},
 {name:'write-during-game',ticket:198,test:'TestR198NoWritesDuringGame',file:'game_camera_mode.go',text:camera.replace('func cameraStageAllowed(stage, phase string) bool {','func cameraStageAllowed(stage, phase string) bool {\n if phase=="InProgress"||phase=="Reconnect"{return true}')},
 {name:'also-patch-wasd',ticket:198,test:'TestR198WASDNeverChanges',file:'game_camera_mode.go',text:camera.replace('patch := map[string]map[string]any{section: {name: replacement}}','patch := map[string]map[string]any{section: {name: replacement,"CameraModeWASD":replacement}}')},
];
const results=[];for(const entry of entries){const original=entry.ticket===197?live:camera;assert.notEqual(entry.text,original,entry.name+' anchor');const mutant=path.join(temp,entry.name+'.go'),overlay=path.join(temp,entry.name+'.json');fs.writeFileSync(mutant,entry.text);fs.writeFileSync(overlay,JSON.stringify({Replace:{[path.join(root,'backend',entry.file)]:mutant}}));const run=spawnSync('go',['test','-overlay='+overlay,'./backend','-run','^'+entry.test+'$','-count=1'],{cwd:root,encoding:'utf8'});const log=(run.stdout||'')+(run.stderr||'');fs.writeFileSync(path.join(temp,entry.name+'.log'),log);assert.notEqual(run.status,0,entry.name+' survived');assert.match(log,new RegExp('--- FAIL: '+entry.test),entry.name+' must fail assertion');assert.doesNotMatch(log,/build failed|SyntaxError|undefined:/);results.push({name:entry.name,test:entry.test,ticket:entry.ticket,killed:true})}
for(const ticket of [197,198]){const dir=path.join(root,'docs/history/reports/r'+ticket);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'mutations.json'),JSON.stringify({results:results.filter(x=>x.ticket===ticket),logs:temp},null,2)+'\n')}console.log(JSON.stringify(results));
